minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  sharp: true
  unrs-resolver: true
  mongodb-memory-server: false

verifyDepsBeforeRun: false
