// In-memory Mongo query model for route regression tests only.
// Does not replace the required real replica-set integration test.
require('mingo/init/system');
const {Query,Aggregator}=require('mingo');
const schema=require('../lib/mongo/schema.json');
module.exports=function(){let tables={},seq=0;const list=t=>tables[t]||(tables[t]=[]);const query=(a,f)=>new Query(f).find(a);function cursor(t,f){let sort={},limit=0;return {sort(s){sort=s;return this},limit(n){limit=n;return this},async toArray(){let r=query(list(t),f).sort(sort).all();if(limit)r=r.slice(0,limit);return structuredClone(r)}}}
 function unique(t,d,except){const keys=[schema[t]?.find(c=>c.pk)?.name].filter(Boolean).map(k=>[k]);if(t==='credentials')keys.push(['username']);if(t==='order_edits')keys.push(['invoice_id','revision']);for(const k of keys)if(list(t).some(x=>x._id!==except&&k.every(f=>x[f]===d[f]))){const e=Error('duplicate');e.code=11000;throw e}}
 const db={collection(t){return {find(f={}){return cursor(t,f)},async findOne(f={}){return (await cursor(t,f).limit(1).toArray())[0]||null},aggregate(p){return {async toArray(){return structuredClone(new Aggregator(p).run(list(t)))}}},async insertOne(d){d=structuredClone(d);d._id??=(++seq).toString(16).padStart(24,'0');unique(t,d);list(t).push(d);return {insertedId:d._id}},async insertMany(ds){for(const d of ds)await this.insertOne(d)},async replaceOne(f,d){const old=query(list(t),f).all()[0];if(!old)return {matchedCount:0};unique(t,d,old._id);tables[t]=list(t).map(x=>x===old?structuredClone(d):x);return {matchedCount:1}},async updateOne(f,u,o={}){let d=query(list(t),f).all()[0],inserted=false;if(!d){if(!o.upsert)return {matchedCount:0};d={...f};inserted=true}d=structuredClone(d);for(const [k,v]of Object.entries(u.$inc||{}))d[k]=(d[k]||0)+v;Object.assign(d,u.$set||{},inserted?u.$setOnInsert||{}:{});if(inserted){await this.insertOne(d);return {matchedCount:0,upsertedCount:1}}await this.replaceOne({_id:d._id},d);return {matchedCount:1}},async deleteOne(f){const d=query(list(t),f).all()[0];tables[t]=list(t).filter(x=>x!==d);return {deletedCount:d?1:0}},async deleteMany(f){const matches=query(list(t),f).all();tables[t]=list(t).filter(x=>!matches.includes(x));return {deletedCount:matches.length}},async createIndex(){},async countDocuments(f={}){return query(list(t),f).count()}}},async command(){return {setName:'MODEL-NOT-REAL-MONGODB'}},listCollections({name}){return {async hasNext(){return !!tables[name]}}},async createCollection(t){list(t)}};
 const client={startSession(){return {async withTransaction(fn){const before=structuredClone(tables);try{return await fn()}catch(e){tables=before;throw e}},async endSession(){}}},async close(){}};
 return {db,client};
}
