import {member,db,json,failure,HttpError,sameOrigin} from '../../../lib/server';
import {canRead,type Member,type StoredRecord} from '../../../lib/permissions';
import {routeInsights,shiftMonth} from '../../../lib/route-insights';
import {indiaDay} from '../../../lib/operations';
import {accessRoute} from '../../../lib/customer-access';
export async function GET(req:Request){try{const viewer=await member(),q=new URL(req.url).searchParams,email=q.get('mr')||viewer.email;if(viewer.role!=='admin'&&email!==viewer.email)throw new HttpError(403,'Only your follow-ups are available.');const mr=await db().prepare("SELECT * FROM members WHERE email=? AND role='mr'").bind(email).first<Member>();if(!mr)throw new HttpError(400,'Select an MR.');const today=indiaDay(),month=today.slice(0,7),raw=(await db().prepare('SELECT * FROM records').all<StoredRecord>()).results,records=raw.map(r=>({...r,data:JSON.parse(r.data)})),customers=raw.filter(r=>r.kind==='Customers'&&canRead(mr,r)).map(r=>({...r,data:JSON.parse(r.data)}));
 const orders=(await db().prepare("SELECT * FROM invoices WHERE mr_email=? AND kind='secondary'").bind(email).all<any>()).results,visits=records.filter(r=>r.kind==='Visits'&&(r.assigned_to?r.assigned_to===email:r.owner===mr.user_id)).sort((a,b)=>(b.data.Date||b.created).localeCompare(a.data.Date||a.created)||b.created.localeCompare(a.created));
 const tasks=(await db().prepare('SELECT * FROM followup_tasks WHERE mr_email=?').bind(email).all<any>()).results,items:any[]=[],push=(id:string,source:string,title:string,due:string,detail:string)=>{const c=customers.find(c=>c.id===id);if(!c)return;const saved=tasks.find(t=>t.customer_id===id&&t.source===source),routeId=accessRoute(mr,c.data),route=routeId?records.find(r=>r.id===routeId)?.data.Name:c.data.Route;items.push({customerId:id,customer:c.data.Name,route:route||'Unassigned',source,title,due:saved?.due||due,notes:saved?.notes||'',status:saved?.status||'Open',saved:!!saved,detail})};
 const seen=new Set<string>();for(const v of visits){const id=v.data['Customer ID']||customers.find(c=>c.data.Name===v.data.Customer)?.id;if(!id||seen.has(id))continue;seen.add(id);if(v.data['Follow-up date'])push(id,'visit:'+v.id,'Visit due',v.data['Follow-up date'],v.data.Response||'Customer follow-up')}
 const commitments=(await db().prepare('SELECT * FROM commitments WHERE mr_email=? AND quantity>fulfilled').bind(email).all<any>()).results;for(const c of commitments){if(orders.find(o=>o.id===c.invoice_id)?.status==='Cancelled')continue;push(c.customer_id,'sample:'+c.id,'Pending sample commitment',today,`${records.find(r=>r.id===c.product_id)?.data.Name||'Product'} · ${c.quantity-c.fulfilled} units pending · ${c.notes||''}`)}
 const insights=routeInsights(mr,month,shiftMonth(month,-1),3,records,orders);for(const row of insights.tables[2].rows){const c=customers.find(c=>c.data.Name===row[0]);if(c)push(c.id,'no-order:'+month,'Visited without order',today,`${row[4]} visit(s) this month; no order recorded.`)}for(const row of insights.tables[3].rows){const c=customers.find(c=>c.data.Name===row[0]);if(c)push(c.id,'inactive:'+month,'Inactive customer',today,`Last order ${row[4]}; no orders in the previous 3 full months or this month.`)}
 for(const t of tasks)if(!items.some(i=>i.customerId===t.customer_id&&i.source===t.source))push(t.customer_id,t.source,'Scheduled follow-up',t.due,'Previously scheduled action');
 return json({items:items.sort((a,b)=>a.due.localeCompare(b.due)),today});
}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const viewer=await member(),b=await req.json() as any,email=viewer.role==='admin'?b.mrEmail:viewer.email;if(viewer.role!=='admin'&&b.mrEmail&&b.mrEmail!==viewer.email)throw new HttpError(403,'You can update only your follow-ups.');const mr=await db().prepare("SELECT * FROM members WHERE email=? AND role='mr'").bind(email).first<Member>(),c=await db().prepare("SELECT * FROM records WHERE id=? AND kind='Customers'").bind(b.customerId).first<StoredRecord>();if(!mr||!c||!canRead(mr,c))throw new HttpError(403,'Customer is not available to this MR.');if(typeof b.source!=='string'||b.source.length>150||typeof b.due!=='string'||!/^20\d{2}-\d{2}-\d{2}$/.test(b.due)||Number.isNaN(Date.parse(b.due))||new Date(b.due).toISOString().slice(0,10)!==b.due||!['Open','Done'].includes(b.status)||typeof b.notes!=='string'||b.notes.length>2000)throw new HttpError(400,'Enter a valid next-action date and notes.');await db().prepare('INSERT INTO followup_tasks(id,mr_email,customer_id,source,due,notes,status,updated) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET due=excluded.due,notes=excluded.notes,status=excluded.status,updated=excluded.updated').bind(email+'|'+b.customerId+'|'+b.source,email,b.customerId,b.source,b.due,b.notes,b.status,new Date().toISOString()).run();return json({ok:true});}catch(e){return failure(e)}}
