import {z} from 'zod';
import {member,db,json,failure,sameOrigin,HttpError} from '../../../lib/server';
import {record,guard} from '../../../lib/operations';
import {unfinishedDraftSQL} from '../../../lib/drafts';
const schema=z.object({id:z.string().min(1).max(100),kind:z.enum(['order','visit','visit_close']),revision:z.number().int().min(0),payload:z.record(z.unknown())});
export async function GET(){try{const m=await member();if(m.role!=='mr')throw new HttpError(403,'Drafts belong to MR accounts.');return json({drafts:(await db().prepare(`SELECT * FROM mr_drafts WHERE mr_email=? AND ${unfinishedDraftSQL} ORDER BY updated DESC`).bind(m.email).all<any>()).results.map(d=>({...d,payload:JSON.parse(d.payload)}))})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const m=await member();if(m.role!=='mr')throw new HttpError(403,'Use your MR account.');const p=schema.safeParse(await req.json());if(!p.success)throw new HttpError(400,'Invalid draft.');const b=p.data;const text=z.string().max(2000),line=z.object({productId:z.string().max(100),qty:z.number().min(0).max(100000),scheme:z.enum(['none','1','2','3'])}),issue=z.object({itemId:z.string().max(100),qty:z.number().min(0).max(100000),commitmentId:z.string().max(100).optional()});const shape=b.kind==='order'?z.object({customerId:text,customerName:text,stockistId:text,date:text,notes:text,visitId:text,lines:z.array(line).max(20),promises:z.array(z.object({productId:text,qty:z.number().min(0).max(100000),notes:text})).max(10)}):b.kind==='visit'?z.object({form:z.record(z.string().max(100),z.string().max(5000))}):z.object({visitId:z.string().max(100),customerName:text,gifts:z.array(issue).max(10),samples:z.array(issue).max(10),notes:text});const payloadCheck=shape.safeParse(b.payload);if(!payloadCheck.success)throw new HttpError(400,'Invalid draft details.');b.payload=payloadCheck.data;if(b.kind==='visit'){for(const key of ['GPS data','Location','Location captured at','Closing GPS'])delete (b.payload.form as any)[key];}if(b.kind==='visit_close'){const v=await record(String(b.payload.visitId),'Visits');if(v.assigned_to!==m.email)throw new HttpError(403,'This visit belongs to another MR.');}const payload=JSON.stringify(b.payload);if(payload.length>25000)throw new HttpError(400,'Draft is too large.');if(b.kind==='visit_close'&&(typeof b.payload.visitId!=='string'))throw new HttpError(400,'Invalid visit draft.');
 const old=await db().prepare('SELECT * FROM mr_drafts WHERE id=?').bind(b.id).first<any>();if(old&&(old.mr_email!==m.email||old.kind!==b.kind))throw new HttpError(403,'This draft belongs to another account.');if(old&&(old.status!=='Active'||old.revision!==b.revision)||!old&&b.revision!==0)throw new HttpError(409,'Draft changed in another screen. Reopen it from Drafts.');
 const finished=b.kind==='order'?await db().prepare('SELECT id FROM invoices WHERE id=?').bind(b.id).first():b.kind==='visit'?await db().prepare('SELECT id FROM records WHERE id=?').bind(b.id).first():await db().prepare("SELECT id FROM records WHERE id=? AND json_extract(data,'$.Status')='Closed'").bind(b.payload.visitId).first();if(finished)throw new HttpError(409,'This draft has already been submitted.');
 await db().batch([guard('version',old?"EXISTS(SELECT 1 FROM mr_drafts WHERE id=? AND mr_email=? AND revision=? AND status='Active')":"NOT EXISTS(SELECT 1 FROM mr_drafts WHERE id=?)",old?[b.id,m.email,b.revision]:[b.id]),guard('version',b.kind==='order'?'NOT EXISTS(SELECT 1 FROM invoices WHERE id=?)':b.kind==='visit'?'NOT EXISTS(SELECT 1 FROM records WHERE id=?)':"NOT EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.Status')='Closed')",[b.kind==='visit_close'?String(b.payload.visitId):b.id]),db().prepare("INSERT INTO mr_drafts(id,mr_email,kind,payload,revision,status,updated) VALUES (?,?,?,?,1,'Active',?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,revision=mr_drafts.revision+1,updated=excluded.updated").bind(b.id,m.email,b.kind,payload,new Date().toISOString())]);return json({ok:true,revision:b.revision+1});}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{sameOrigin(req);const m=await member(),b=await req.json() as any;if(typeof b.id!=='string'||!Number.isInteger(b.revision))throw new HttpError(400,'Choose a draft.');const d=await db().prepare('SELECT * FROM mr_drafts WHERE id=? AND mr_email=?').bind(b.id,m.email).first<any>();if(!d)throw new HttpError(404,'Draft unavailable.');await db().batch([guard('version','EXISTS(SELECT 1 FROM mr_drafts WHERE id=? AND revision=?)',[b.id,b.revision]),db().prepare("UPDATE mr_drafts SET status='Discarded',revision=revision+1 WHERE id=? AND mr_email=?").bind(b.id,m.email)]);return json({ok:true})}catch(e){return failure(e)}}
