import {admin,db,json,failure,HttpError} from '../../../lib/server';
import {indiaDay} from '../../../lib/operations';
import {comparison,overdueActions,pendingMonths} from '../../../lib/admin-overview';
import {canRead,type Member,type StoredRecord} from '../../../lib/permissions';
import {idList} from '../../../lib/field-rules';
import {accessRoute} from '../../../lib/customer-access';
export async function GET(req:Request){try{await admin();const q=new URL(req.url).searchParams,mode=q.get('mode')||'overview',month=q.get('month')||indiaDay().slice(0,7);
 if(mode==='audit'){const after=q.get('after')||'',kind=q.get('kind')||'',args:any[]=[];let where='1=1';if(after){let cursor:any;try{cursor=JSON.parse(after)}catch{throw new HttpError(400,'Invalid history cursor.')}if(typeof cursor.created!=='string'||typeof cursor.id!=='string')throw new HttpError(400,'Invalid cursor.');where+=' AND (created<? OR (created=? AND id<?))';args.push(cursor.created,cursor.created,cursor.id)}if(kind){where+=' AND entity_kind=?';args.push(kind)}const rows=(await db().prepare(`SELECT * FROM admin_audit WHERE ${where} ORDER BY created DESC,id DESC LIMIT 101`).bind(...args).all<any>()).results;const page=rows.slice(0,100),last=page.at(-1);return json({events:page,next:rows.length>100?JSON.stringify({created:last.created,id:last.id}):null});}
 if(!/^20\d{2}-(0[1-9]|1[0-2])$/.test(month))throw new HttpError(400,'Choose a valid month.');
 const [rr,mm,ii,bb,ss,tt,cc,ll,aa,balances]=await Promise.all([db().prepare('SELECT * FROM records').all<StoredRecord>(),db().prepare("SELECT * FROM members WHERE role='mr'").all<Member>(),db().prepare('SELECT * FROM invoices').all<any>(),db().prepare('SELECT * FROM benefit_movements').all<any>(),db().prepare('SELECT b.*,COALESCE((SELECT SUM(quantity) FROM stock_reservations r WHERE r.stockist_id=b.stockist_id AND r.product_id=b.product_id),0) AS reserved,(SELECT MAX(created) FROM stock_movements m WHERE m.stockist_id=b.stockist_id AND m.product_id=b.product_id) AS last_movement FROM stock_balances b').all<any>(),db().prepare('SELECT * FROM followup_tasks').all<any>(),db().prepare('SELECT * FROM commitments WHERE quantity>fulfilled').all<any>(),db().prepare('SELECT * FROM period_locks').all<any>(),db().prepare('SELECT r.mr_email,r.report FROM period_reports r JOIN period_locks l ON l.closure_id=r.closure_id AND l.closed=1 WHERE r.month=?').bind(month).all<any>(),db().prepare('SELECT * FROM benefit_balances').all<any>()]);
 const records=rr.results.map(r=>({...r,data:JSON.parse(r.data)})),reps=mm.results,name=(id:string)=>records.find(r=>r.id===id)?.data.Name||id,memberName=(email:string)=>reps.find(m=>m.email===email)?.name||email,invoices=ii.results.map(i=>({...i,items:JSON.parse(i.items)})),stock=ss.results.map(s=>({...s,agency:name(s.stockist_id),product:name(s.product_id),available:s.quantity-s.reserved,lastMovement:s.last_movement,daysIdle:s.last_movement?Math.floor((Date.now()-Date.parse(s.last_movement))/86400000):null}));
 if(mode==='profile'){const m=reps.find(m=>m.email===q.get('mr'));if(!m)throw new HttpError(404,'Select an MR.');const customers=rr.results.filter(r=>r.kind==='Customers'&&canRead(m,r)).map(r=>{const d=JSON.parse(r.data),rid=accessRoute(m,d);return {id:r.id,name:d.Name,route:rid?name(rid):d.Route,phone:d['Mobile 1']||d.Phone,category:d['Customer category']||d.Type}}),own=(r:any)=>r.assigned_to?r.assigned_to===m.email:r.owner===m.user_id;const archived=aa.results.find(a=>a.mr_email===m.email);return json({member:m,month,comparison:comparison(m,month,records,invoices,bb.results,archived?JSON.parse(archived.report).admin:undefined),routes:idList(m.route_ids).map(name),districts:idList(m.district_ids).map(name),agencies:idList(m.stockist_ids).map(name),customers,stock:stock.filter(s=>idList(m.stockist_ids).includes(s.stockist_id)),attendance:records.filter(r=>r.kind==='Attendance'&&own(r)&&(r.data.Date||r.created).startsWith(month)),visits:records.filter(r=>r.kind==='Visits'&&own(r)&&(r.data.Date||r.created).startsWith(month)),orders:invoices.filter(i=>i.kind==='secondary'&&i.mr_email===m.email&&i.date.startsWith(month)).map(i=>({...i,customer:name(i.customer_id),agency:name(i.stockist_id)})),allocations:bb.results.filter(b=>b.mr_email===m.email&&new Date(b.created).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}).startsWith(month)).map(b=>({...b,item:name(b.item_id),customer:name(b.customer_id)})),balances:balances.results.filter(b=>b.mr_email===m.email).map(b=>({...b,item:name(b.item_id)}))});}
 return json({month,comparison:reps.map(m=>{const a=aa.results.find(r=>r.mr_email===m.email);return comparison(m,month,records,invoices,bb.results,a?JSON.parse(a.report).admin:undefined)}),stock,overdue:overdueActions(indiaDay(),reps,records,tt.results),samples:cc.results.filter(c=>invoices.find(i=>i.id===c.invoice_id)?.status!=='Cancelled').map(c=>({...c,mr:memberName(c.mr_email),customer:name(c.customer_id),product:name(c.product_id),pending:c.quantity-c.fulfilled,order:invoices.find(i=>i.id===c.invoice_id)?.number})),months:pendingMonths(indiaDay(),records,invoices,ll.results)});
}catch(e){return failure(e)}}
