import {orderChangeBlock} from '../../../lib/order-edit-policy';
import {audit} from '../../../lib/admin-audit';
import {digest} from '../../../lib/passwords';
import {periodGuard,assertOpen,stateSQL} from '../../../lib/periods';
import {orderStock,summaryStatements,availableGuard} from '../../../lib/order-stock';
import {orderMessages} from '../../../lib/order-messages';
import {sendWhatsApp} from '../../../lib/whatsapp';
import {z} from 'zod';
import {member,db,json,sameOrigin,failure,HttpError,notification} from '../../../lib/server';
import {OWNER_EMAIL,type Member} from '../../../lib/permissions';
import {priceLine,idList,type PricedLine} from '../../../lib/field-rules';
import {record,customer,stockistAllowed,ledgerFailure,indiaDay,guard} from '../../../lib/operations';
import {stockistIDs,customerCategory} from '../../../lib/customers';
const line=z.object({productId:z.string().min(1),qty:z.number().int().min(1).max(100000),scheme:z.enum(['none','1','2','3']).default('none')});
const schema=z.object({id:z.string().uuid(),kind:z.enum(['primary','secondary']),stockistId:z.string().min(1),customerId:z.string().default(''),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(d=>!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d),number:z.string().trim().max(100).default(''),visitId:z.string().default(''),notes:z.string().max(2000).default(''),lines:z.array(line).min(1).max(20),commitments:z.array(z.object({productId:z.string(),qty:z.number().int().min(1).max(10000),notes:z.string().max(500).default('')})).max(10).default([])});
export async function GET(){try{
 const m=await member(),ids=idList(m.stockist_ids);const stock=(await db().prepare('SELECT * FROM stock_balances').all<{stockist_id:string}>()).results.filter(r=>m.role==='admin'||ids.includes(r.stockist_id));
 for(const b of stock as any[]){const r=await db().prepare('SELECT COALESCE(SUM(quantity),0) AS qty FROM stock_reservations WHERE stockist_id=? AND product_id=?').bind(b.stockist_id,b.product_id).first<{qty:number}>();b.reserved=r?.qty||0;b.available=b.quantity-b.reserved;}
 const lockedMonths=(await db().prepare('SELECT month FROM period_locks WHERE closed=1').all<{month:string}>()).results.map(r=>r.month);
 const invoices=(await db().prepare('SELECT * FROM invoices ORDER BY created DESC LIMIT 1000').all<Record<string,any>>()).results.filter(r=>m.role==='admin'||(r.kind==='primary'?ids.includes(r.stockist_id):r.mr_email===m.email)).map(r=>({...r,changeBlockReason:orderChangeBlock(m.role,r.date,indiaDay(),lockedMonths),items:JSON.parse(r.items).map((l:PricedLine)=>m.role==='mr'&&r.kind==='primary'?{productId:l.productId,name:l.name,qty:l.qty,free:l.free,scheme:l.scheme}:l)}));
 const promises=(await db().prepare('SELECT * FROM commitments WHERE fulfilled<quantity ORDER BY created').all<Record<string,any>>()).results.filter(r=>m.role==='admin'||r.mr_email===m.email);
 const edits=(await db().prepare('SELECT * FROM order_edits ORDER BY created DESC LIMIT 1000').all<Record<string,any>>()).results.filter(r=>m.role==='admin'||r.mr_email===m.email);const requests=(await db().prepare("SELECT * FROM workflow_requests WHERE kind='order_edit' ORDER BY created DESC").all<any>()).results.filter(r=>m.role==='admin'||r.mr_email===m.email);return json({stock,invoices,commitments:promises,edits,requests});
}catch(e){return failure(e)}}
export async function POST(req:Request){try{
 sameOrigin(req);const m=await member();const parsed=schema.safeParse(await req.json());if(!parsed.success)throw new HttpError(400,'Choose a stockist and valid product quantities.');const b=parsed.data;await assertOpen(b.date);
 if(b.kind==='primary'&&m.role!=='admin')throw new HttpError(403,'Only Admin can bill primary stock.');
 if(b.kind==='secondary'&&m.role==='admin')throw new HttpError(403,'Secondary orders must be entered using the responsible MR account.');
 if(!stockistAllowed(m,b.stockistId))throw new HttpError(403,'This stockist is not assigned to you.');
 const previous=await db().prepare('SELECT id,mr_email FROM invoices WHERE id=?').bind(b.id).first<{id:string;mr_email:string}>();if(previous){if(previous.mr_email!==m.email)throw new HttpError(403,'This invoice belongs to another account.');return json({ok:true,id:previous.id,alreadySaved:true});}
 const draft=await db().prepare('SELECT mr_email,kind,status FROM mr_drafts WHERE id=?').bind(b.id).first<any>();if(draft&&(draft.mr_email!==m.email||draft.kind!=='order'||draft.status!=='Active'))throw new HttpError(403,'Order draft unavailable for this account.');
 const stockist=await record(b.stockistId,'Stockists');let c:Awaited<ReturnType<typeof customer>>|null=null;
 if(b.kind==='secondary'){
  if(b.date!==indiaDay())throw new HttpError(400,'MR orders must use today’s date.');c=await customer(m,b.customerId);
  if(customerCategory(c.details)==='Medical / Clinic'&&!stockistIDs(c.details).includes(b.stockistId))throw new HttpError(400,'Select a stockist linked to this medical / clinic.');
  if(b.visitId){const visit=await record(b.visitId,'Visits');if(visit.assigned_to!==m.email||visit.details.Status==='Closed'||visit.details['Customer ID']!==b.customerId)throw new HttpError(400,'Select your open visit for this customer.');}
 }
 if(new Set(b.lines.map(l=>l.productId)).size!==b.lines.length)throw new HttpError(400,'Add each product once per invoice.');
 const items:PricedLine[]=[];for(const l of b.lines){const product=await record(l.productId,'Products');try{items.push(priceLine(product.details,l.productId,l.qty,l.scheme,b.kind==='primary'))}catch(e){throw new HttpError(400,(e as Error).message)}}
 const now=new Date().toISOString(),number=b.number||`${b.kind==='primary'?'PRI':'ORD'}-${b.date.replaceAll('-','')}-${b.id.slice(0,8).toUpperCase()}`,subtotal=items.reduce((n,l)=>n+l.subtotal,0),total=items.reduce((n,l)=>n+l.total,0);
 const statements=[periodGuard(b.date),db().prepare('INSERT INTO invoices(id,kind,stockist_id,customer_id,mr_email,number,date,items,subtotal,total,visit_id,notes,created,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.id,b.kind,b.stockistId,b.customerId,m.email,number,b.date,JSON.stringify(items),subtotal,total,b.visitId,b.notes,now,b.kind==='primary'?'Delivered':'Placed')];
 if(b.kind==='primary')for(const item of items){statements.push(db().prepare('INSERT INTO stock_movements(id,invoice_id,stockist_id,product_id,quantity,created) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),b.id,b.stockistId,item.productId,item.qty+item.free,now),db().prepare('INSERT INTO stock_balances(id,stockist_id,product_id,quantity) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET quantity=quantity+excluded.quantity').bind(b.stockistId+'|'+item.productId,b.stockistId,item.productId,item.qty+item.free),availableGuard(b.stockistId,item.productId));}
 else{const order={id:b.id,stockist_id:b.stockistId,status:'Placed',date:b.date,number,created:now,notes:b.notes};statements.push(...orderStock(null,order,items),...summaryStatements(order,items,m,c!.details,stockist.details));}
 for(const p of b.commitments){if(b.kind!=='secondary')throw new HttpError(400,'Sample commitments belong to customer orders.');await record(p.productId,'Products');statements.push(db().prepare('INSERT INTO commitments(id,invoice_id,customer_id,mr_email,product_id,quantity,fulfilled,notes,created) VALUES (?,?,?,?,?,?,0,?,?)').bind(crypto.randomUUID(),b.id,b.customerId,m.email,p.productId,p.qty,p.notes,now));}
 if(b.kind==='primary'){const reps=(await db().prepare("SELECT * FROM members WHERE role='mr' AND status='active'").all<Member>()).results;for(const rep of reps)if(idList(rep.stockist_ids).includes(b.stockistId))statements.push(notification(rep.email,'Stockist stock updated',`${stockist.details.Name} · Invoice ${number} · ₹${(subtotal/100).toFixed(2)} excluding GST`,'Stock balance',b.id));}
 else statements.push(notification(OWNER_EMAIL,'New MR order',`${m.name} · ${c!.details.Name} · ₹${(total/100).toFixed(2)}`,'Orders',b.id));
 const messages=b.kind==='secondary'?await orderMessages(m,{id:b.id,number,date:b.date,stockistId:b.stockistId,customer:c!.details.Name,items,subtotal,total,notes:`Status: Placed. ${b.notes}`}):null;if(messages)statements.push(...messages.statements);
 try{await db().batch(statements)}catch(e){ledgerFailure(e)}if(messages)await Promise.allSettled(messages.ids.map(sendWhatsApp));return json({ok:true,id:b.id});
}catch(e){return failure(e)}}

const editSchema=z.object({id:z.string().uuid(),requestId:z.string().uuid(),revision:z.number().int().min(1),lines:z.array(line).min(1).max(20),notes:z.string().max(2000).default(''),reprice:z.boolean().default(false)});
export async function PATCH(req:Request){try{
 sameOrigin(req);const actor=await member(),raw=await req.json() as any;let b:any=raw,review:any=null,reviewStamp='';
 if(raw.action==='approve'||raw.action==='reject'){if(actor.role!=='admin')throw new HttpError(403,'Admin approval required.');review=await db().prepare("SELECT * FROM workflow_requests WHERE id=? AND kind='order_edit' AND status='Pending'").bind(raw.requestId).first<any>();if(!review)throw new HttpError(409,'Request already reviewed.');if(raw.action==='reject'){await db().batch([audit(actor,'Order edit rejected','Orders',review.record_id,JSON.parse(review.body),null,String(raw.reason||'Rejected by Admin')),db().prepare("UPDATE workflow_requests SET status='Rejected',reviewed=?,reason=? WHERE id=? AND status='Pending'").bind(new Date().toISOString(),String(raw.reason||'Rejected by Admin'),review.id),notification(review.mr_email,'Order change rejected',String(raw.reason||'Contact Admin.'),'Orders',review.record_id)]);return json({ok:true})}reviewStamp=(await db().prepare(stateSQL).first<{stamp:string}>())!.stamp;if(raw.hash!==await digest(reviewStamp))throw new HttpError(409,'Data changed since review. Refresh approvals before approving.');b=JSON.parse(review.body);}
 const old=await db().prepare("SELECT * FROM invoices WHERE id=? AND kind='secondary'").bind(b.id).first<any>();if(!old||(actor.role!=='admin'&&old.mr_email!==actor.email))throw new HttpError(403,'You can change only your own orders.');await assertOpen(old.date);const changeBlock=orderChangeBlock(actor.role,old.date,indiaDay());if(changeBlock)throw new HttpError(409,changeBlock);
 const mr=await db().prepare('SELECT * FROM members WHERE email=?').bind(old.mr_email).first<Member>();if(!mr)throw new HttpError(404,'MR not found.');
 let items=JSON.parse(old.items) as PricedLine[],status=old.status,accepted=old.accepted,notes=old.notes;const requestId=review?review.id:raw.requestId;
 if(typeof requestId!=='string'||!requestId)throw new HttpError(400,'Request ID required.');
 const retry=await db().prepare('SELECT invoice_id FROM order_edits WHERE id=?').bind(requestId).first<any>();if(retry){if(retry.invoice_id!==old.id)throw new HttpError(409,'Request already used.');return json({ok:true,alreadySaved:true})}
 if(old.revision!==b.revision)throw new HttpError(409,'Order changed. Refresh and submit a new request.');
 if(raw.action==='status'&&raw.status==='Cancelled'&&(typeof raw.reason!=='string'||raw.reason.trim().length<3))throw new HttpError(400,'Record a cancellation reason.');
 if(raw.action==='accept'){if(actor.role!=='admin'||status!=='Placed')throw new HttpError(403,'Only Admin can record agency acceptance for a placed order.');accepted=1;}
 else if(raw.action==='status'){if(!['Delivered','Cancelled'].includes(raw.status))throw new HttpError(400,'Choose Delivered or Cancelled.');if(actor.role!=='admin'&&(old.accepted||old.status!=='Placed'||raw.status!=='Cancelled'))throw new HttpError(403,'Admin must change an accepted or delivered order.');if(old.status==='Cancelled')throw new HttpError(409,'A cancelled order cannot be changed.');status=raw.status;}
 else{const parsed=editSchema.safeParse(b);if(!parsed.success)throw new HttpError(400,'Choose valid products and quantities.');b=parsed.data;if(old.status==='Cancelled')throw new HttpError(409,'Cancelled orders cannot be edited.');if(actor.role!=='admin'&&(!stockistAllowed(actor,old.stockist_id)))throw new HttpError(403,'Agency no longer assigned.');
 if(actor.role!=='admin'&&(old.accepted||old.status==='Delivered'||b.reprice)){const existing=await db().prepare('SELECT id FROM workflow_requests WHERE id=?').bind(b.requestId).first();if(!existing)await db().batch([periodGuard(old.date),db().prepare("INSERT INTO workflow_requests(id,kind,mr_email,record_id,body,status,created) VALUES (?,'order_edit',?,?,?,'Pending',?)").bind(b.requestId,actor.email,old.id,JSON.stringify(b),new Date().toISOString()),notification(OWNER_EMAIL,'Order edit approval requested',`${actor.name} · ${old.number}${b.reprice?' · Repricing requested':''}`,'Approvals',old.id)]);return json({ok:true,pendingApproval:true})}
 if(new Set(b.lines.map((l:any)=>l.productId)).size!==b.lines.length)throw new HttpError(400,'Add each product once.');const previous=items;items=[];for(const l of b.lines){const product=await record(l.productId,'Products');const saved=previous.find(i=>i.productId===l.productId);let q:PricedLine;try{q=saved&&!b.reprice&&saved.qty===l.qty&&saved.scheme===l.scheme?{...saved}:priceLine(saved&&!b.reprice?{...product.details,PTR:String(saved.rate/100),'Retail offer enabled':'No','GST %':String(saved.gst)}:product.details,l.productId,l.qty,l.scheme,false)}catch(e){throw new HttpError(400,(e as Error).message)}if(saved&&!b.reprice){q.rate=saved.rate;q.gst=saved.gst;q.mrp=saved.mrp;q.ptr=saved.ptr;q.subtotal=Math.round(saved.rate*l.qty);q.total=Math.round(q.subtotal*(1+saved.gst/100));if(saved.qty===l.qty&&saved.scheme===l.scheme)q.free=saved.free;}items.push(q)}notes=b.notes;
 }
 const c=await record(old.customer_id,'Customers'),stockist=await record(old.stockist_id,'Stockists'),now=new Date().toISOString(),revision=old.revision+1,subtotal=items.reduce((n,l)=>n+l.subtotal,0),total=items.reduce((n,l)=>n+l.total,0),after={...old,items:JSON.stringify(items),subtotal,total,notes,revision,status,accepted};
 const statements=[...(review?[guard('version',`(${stateSQL})=?`,[reviewStamp])]:[]),periodGuard(old.date),guard('version','EXISTS(SELECT 1 FROM invoices WHERE id=? AND revision=?)',[old.id,old.revision]),db().prepare('INSERT INTO order_edits(id,invoice_id,revision,mr_email,before_data,after_data,created) VALUES (?,?,?,?,?,?,?)').bind(requestId,old.id,old.revision,mr.email,JSON.stringify(old),JSON.stringify(after),now),db().prepare('UPDATE invoices SET items=?,subtotal=?,total=?,notes=?,revision=?,status=?,accepted=? WHERE id=?').bind(JSON.stringify(items),subtotal,total,notes,revision,status,accepted,old.id),...orderStock(old,after,items),...summaryStatements(after,items,mr,c.details,stockist.details)];
 if(review)statements.push(guard('version',"EXISTS(SELECT 1 FROM workflow_requests WHERE id=? AND status='Pending')",[review.id]),db().prepare("UPDATE workflow_requests SET status='Approved',reviewed=?,reason=? WHERE id=?").bind(now,`Approved by ${actor.name}`,review.id));
 if(status==='Cancelled')statements.push(db().prepare('UPDATE commitments SET quantity=fulfilled WHERE invoice_id=?').bind(old.id));
 if(actor.role==='admin')statements.push(audit(actor,review?(b.reprice?'Order repricing approved':'Order edit approved'):raw.action==='accept'?'Agency acceptance recorded':raw.action==='status'?`Order ${status.toLowerCase()}`:'Order updated','Orders',old.id,old,after,String(raw.reason|| (review?'Reviewed proposed order changes':status==='Delivered'?'Delivery confirmed by Admin':'Admin order update'))));
 const messages=await orderMessages(mr,{id:old.id,number:old.number,date:old.date,stockistId:old.stockist_id,customer:c.details.Name,items,subtotal,total,notes:`Status: ${status}. ${notes}`},revision);statements.push(...messages.statements,notification(OWNER_EMAIL,'Order updated',`${mr.name} · ${old.number} · ${status}`,'Orders',old.id),notification(mr.email,'Order updated',`${old.number} · ${status}${review?' · Admin approved':''}`,'Orders',old.id));
 try{await db().batch(statements)}catch(e){ledgerFailure(e)}await Promise.allSettled(messages.ids.map(sendWhatsApp));return json({ok:true,revision});
}catch(e){return failure(e)}}
