'use client';
import {useState,type FormEvent} from 'react';
import {ShieldCheck,BriefcaseBusiness,Eye,EyeOff,LoaderCircle,LockKeyhole} from 'lucide-react';
export function AccountLogin(){
 const [role,setRole]=useState<'admin'|'mr'>('mr'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||'Unable to log in.');location.assign('/')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <div className="login-page"><div className="login-brand"><div className="brand-mark">V</div><div><strong>VETMECH<span>FIELD</span></strong><small>The fieldwork workspace</small></div></div><div className="login-layout"><div className="login-intro"><div className="label-pill"><LockKeyhole size={16}/> Your VETMECH account</div><h1>Your team.<br/>Your territory.<br/><em>One workspace.</em></h1><p>Plan visits, manage stockist orders and follow your daily progress.</p></div><section className="login-panel"><span className="eyebrow">WELCOME TO VETMECH</span><h2>{role==='admin'?'Admin login':'MR login'}</h2><div className="account-tabs" role="group" aria-label="Choose workspace"><button type="button" aria-pressed={role==='admin'} className={role==='admin'?'primary':'secondary'} onClick={()=>{setRole('admin');setError('')}}><ShieldCheck size={18}/>Admin</button><button type="button" aria-pressed={role==='mr'} className={role==='mr'?'primary':'secondary'} onClick={()=>{setRole('mr');setError('')}}><BriefcaseBusiness size={18}/>MR</button></div><form onSubmit={submit} className="account-form"><label>Username<input autoComplete="username" autoCapitalize="none" spellCheck={false} required minLength={3} maxLength={50} value={username} onChange={e=>setUsername(e.target.value)} placeholder={role==='admin'?'Your Admin username':'Your MR username'}/></label><label>Password<div className="password-input"><input type={show?'text':'password'} autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><button className="icon-button" type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary full-button" disabled={busy}>{busy&&<LoaderCircle className="spin" size={18}/>} {busy?'Logging in…':'Log in'}</button></form><p className="secure-caption">Forgot your password? Contact your Admin.</p><p className="secure-caption">Your account opens its assigned workspace automatically.</p></section></div><footer>VETMECH PHARMACEUTICALS PRIVATE LIMITED</footer></div>
}
export function PasswordForm(){
 const [currentPassword,setCurrent]=useState(''),[newPassword,setNew]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(newPassword!==confirm){setError('New passwords do not match.');return}setBusy(true);try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword,newPassword})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||'Unable to change password.');location.assign('/')}catch(e){setError((e as Error).message);setBusy(false)}}
 return <form className="account-form" onSubmit={submit}><label>Current password<input type="password" autoComplete="current-password" required maxLength={128} value={currentPassword} onChange={e=>setCurrent(e.target.value)}/></label><label>New password<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={newPassword} onChange={e=>setNew(e.target.value)}/><small>At least 12 characters. A memorable phrase works well.</small></label><label>Confirm new password<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p>After saving, log in again with your new password. All existing sessions will end.</p>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Saving…':'Change password'}</button></form>
}
