'use client';
import {MonthlyTargets} from './monthly-report';
import {idList} from '../lib/field-rules';
import {useMemo,useState} from 'react';
import {Users,MapPin,BarChart3,Target,Plus,ChevronRight,Package,Route,Building2,Stethoscope,CalendarDays,Activity,Navigation,ExternalLink,Clock,Gift,Download,Search} from 'lucide-react';
import type {Member} from '../lib/permissions';
import {money,today,recordValue,dateLabel,initials,type FieldRecord} from '../lib/ui-config';
import {parseGPS} from '../lib/business';
type Props={rows:FieldRecord[];team:Member[];go:(tab:string)=>void;open:(kind:string,record?:FieldRecord|null,defaults?:Record<string,string>)=>void;openTeam:(m:Member|null)=>void;tab:string};
function attributed(r:FieldRecord,m:Member){return r.assigned_to?r.assigned_to===m.email:!!m.user_id&&r.owner===m.user_id}
function csvDownload(headers:string[],data:(string|number)[][],name:string){const csv=[headers,...data].map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export function SampleBalances({rows,team,isAdmin}:{rows:FieldRecord[];team:Member[];isAdmin:boolean}){
 const [filter,setFilter]=useState('');
 const balances=useMemo(()=>{
  const map=new Map<string,{email:string;name:string;product:string;issued:number;given:number;returned:number}>();
  for(const r of rows.filter(r=>r.kind==='Samples')){const key=r.assigned_to+'|'+r.data.Product;const item=map.get(key)||{email:r.assigned_to,name:team.find(m=>m.email===r.assigned_to)?.name||r.data.Representative||'Unassigned legacy entry',product:r.data.Product||'Unknown product',issued:0,given:0,returned:0};const qty=Number(r.data.Quantity||0);if(r.data.Movement==='Issued to rep')item.issued+=qty;else if(r.data.Movement==='Returned')item.returned+=qty;else item.given+=qty;map.set(key,item)}
  return Array.from(map.values()).filter(r=>!filter||r.email===filter)
 },[rows,team,filter]);
 return <section className="panel sample-overview"><div className="panel-heading"><h2><Gift size={20}/>{isAdmin?'MR sample balances':'My sample stock'}</h2>{isAdmin&&<select aria-label="Sample balance MR filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All representatives</option>{team.filter(m=>m.role==='mr').map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select>}</div>{balances.length?<div className="sample-balance-grid">{balances.map(b=><article key={b.email+b.product} className="sample-balance-card"><div><h3>{b.product}</h3>{isAdmin&&<p>{b.name}</p>}</div><strong className={b.issued-b.given-b.returned<0?'negative':''}>{b.issued-b.given-b.returned}<small>available</small></strong><div className="sample-counts"><span>Allotted <b>{b.issued}</b></span><span>Given <b>{b.given}</b></span><span>Returned <b>{b.returned}</b></span></div></article>)}</div>:<p className="empty-inline">{isAdmin?'Allot samples to an MR to begin tracking their product balance.':'Your Admin’s sample allotments will appear here.'}</p>}<p className="footnote">All-time quantity balance = allotted − given to doctors − returned. Each product and MR is tracked separately.</p></section>
}
export function AdminWorkspace({rows,team,go,open,openTeam,tab}:Props){
 const [month,setMonth]=useState(today().slice(0,7)),[selectedMR,setSelectedMR]=useState(''),[selectedDistrict,setSelectedDistrict]=useState(''),[selectedHQ,setSelectedHQ]=useState(''),[kindFilter,setKindFilter]=useState('');
 const districtsOf=(m:Member)=>idList(m.district_ids).map(id=>rows.find(r=>r.id===id)?.data.Name).filter(Boolean).concat(m.district?[m.district]:[]);
 const reps=team.filter(m=>m.role==='mr'),filteredReps=reps.filter(m=>(!selectedMR||m.email===selectedMR)&&(!selectedDistrict||districtsOf(m).includes(selectedDistrict))&&(!selectedHQ||m.headquarters===selectedHQ));
 const activityKinds=['Visits','Attendance','Tour plan','Orders','Secondary sales','Samples','Expenses'];
 const monthRows=rows.filter(r=>(r.data.Date||r.created).startsWith(month));
 const performance=filteredReps.map(m=>{const mine=monthRows.filter(r=>attributed(r,m)),visits=mine.filter(r=>r.kind==='Visits'),sales=mine.filter(r=>r.kind==='Secondary sales').reduce((a,r)=>a+recordValue(r),0),orders=mine.filter(r=>(r.kind==='Orders'&&r.data.Status!=='Cancelled')||(r.kind==='Secondary sales'&&r.data['Invoice ID'])).reduce((a,r)=>a+recordValue(r),0),days=new Set(mine.filter(r=>r.kind==='Attendance'&&r.data.Action==='Check in').map(r=>r.data.Date)).size,expenses=mine.filter(r=>r.kind==='Expenses'&&r.data.Status!=='Rejected').reduce((a,r)=>a+Number(r.data.Amount||0),0);return {m,visits:visits.length,doctors:new Set(visits.map(r=>r.data.Customer)).size,sales,orders,days,expenses,target:Number(rows.find(r=>r.id===`monthly-target:${m.email}:${month}`)?.data['MR monthly target']??m.target),percent:Number(rows.find(r=>r.id===`monthly-target:${m.email}:${month}`)?.data['MR monthly target']??m.target)?sales/Number(rows.find(r=>r.id===`monthly-target:${m.email}:${month}`)?.data['MR monthly target']??m.target)*100:0}});
 const assignedActivity=monthRows.filter(r=>activityKinds.includes(r.kind)&&filteredReps.some(m=>attributed(r,m))&&(!kindFilter||r.kind===kindFilter));
 const unassigned=monthRows.filter(r=>activityKinds.includes(r.kind)&&!reps.some(m=>attributed(r,m))).length;
 const attendanceToday=rows.filter(r=>r.kind==='Attendance'&&r.data.Date===today()&&r.data.Action==='Check in'&&reps.some(m=>attributed(r,m)));
 const sales=monthRows.filter(r=>r.kind==='Secondary sales').reduce((a,r)=>a+recordValue(r),0),ordersAwaiting=rows.filter(r=>r.kind==='Orders'&&!['Supplied','Closed','Cancelled'].includes(r.data.Status)).length,expensesPending=rows.filter(r=>r.kind==='Expenses'&&r.data.Status==='Submitted').length;
 const locations=filteredReps.map(m=>{const history=rows.filter(r=>['Visits','Attendance'].includes(r.kind)&&attributed(r,m)&&parseGPS(r.data.Location||'')).sort((a,b)=>(b.data['Location captured at']||b.created).localeCompare(a.data['Location captured at']||a.created));return {m,latest:history[0],history}});
 const districtOptions=Array.from(new Set(reps.flatMap(m=>districtsOf(m)))),hqOptions=Array.from(new Set(reps.filter(m=>!selectedDistrict||districtsOf(m).includes(selectedDistrict)).map(m=>m.headquarters).filter(Boolean)));
 const controls=<div className="admin-filters">{tab!=='Locations'&&<label>Month<input type="month" aria-label="Reporting month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}<label>Representative<select value={selectedMR} onChange={e=>setSelectedMR(e.target.value)}><option value="">All MRs</option>{reps.map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select></label><label>District<select value={selectedDistrict} onChange={e=>{setSelectedDistrict(e.target.value);setSelectedHQ('')}}><option value="">All districts</option>{districtOptions.map(d=><option key={d}>{d}</option>)}</select></label><label>Headquarters<select value={selectedHQ} onChange={e=>setSelectedHQ(e.target.value)}><option value="">All headquarters</option>{hqOptions.map(h=><option key={h}>{h}</option>)}</select></label></div>;
 const performanceTable=<>{performance.length?<><div className="performance-table"><table><thead><tr><th>Representative</th><th>Target</th><th>Secondary sales</th><th>Achievement</th><th>Orders</th><th>Visits</th><th>Doctors covered</th><th>Working days</th><th>Expenses</th></tr></thead><tbody>{performance.map(p=><tr key={p.m.email}><td><b>{p.m.name}</b><small>{p.m.headquarters||p.m.district||'No HQ assigned'}</small></td><td>{money(p.target)}</td><td>{money(p.sales)}</td><td><div className="mini-progress"><span>{p.percent.toFixed(1)}%</span><i><em style={{width:`${Math.min(p.percent,100)}%`}}/></i></div></td><td>{money(p.orders)}</td><td>{p.visits}</td><td>{p.doctors}</td><td>{p.days}</td><td>{money(p.expenses)}</td></tr>)}</tbody></table></div><div className="performance-mobile">{performance.map(p=><article key={p.m.email}><div className="rep-summary-head"><span className="avatar">{initials(p.m.name)}</span><div><b>{p.m.name}</b><small>{p.m.headquarters||p.m.district||'No HQ assigned'}</small></div><strong>{p.percent.toFixed(1)}%</strong></div><div className="mini-progress"><i><em style={{width:`${Math.min(p.percent,100)}%`}}/></i></div><dl><div><dt>Secondary sales</dt><dd>{money(p.sales)}</dd></div><div><dt>Monthly target</dt><dd>{money(p.target)}</dd></div><div><dt>Orders generated</dt><dd>{money(p.orders)}</dd></div><div><dt>Visits / doctors</dt><dd>{p.visits} / {p.doctors}</dd></div><div><dt>Working days</dt><dd>{p.days}</dd></div><div><dt>Expenses</dt><dd>{money(p.expenses)}</dd></div></dl></article>)}</div></>:<div className="empty-state"><Users size={30}/><h3>No representatives match</h3><p>Add your MRs or change the filters to review performance.</p><button className="text-button" onClick={()=>openTeam(null)}>Add representative</button></div>}</>;
 if(tab==='Dashboard')return <>
 <MonthlyTargets revision={rows}/>
 <section className="admin-intro"><div><span className="eyebrow">MANAGE · ALLOT · MONITOR</span><h2>Your field team, at a glance.</h2><p>{reps.filter(m=>m.status==='active').length} active MRs · {new Set(attendanceToday.map(r=>r.assigned_to||r.owner)).size} recorded check-ins today</p></div><button className="primary" onClick={()=>openTeam(null)}><Plus size={18}/>Create MR</button></section>
 <div className="stats">{[['Active MRs',String(reps.filter(m=>m.status==='active').length),'Manage your field force',Users,'green'],['Doctors & customers',String(rows.filter(r=>r.kind==='Customers').length),'Across all territories',Stethoscope,'blue'],['Routes',String(rows.filter(r=>r.kind==='Routes').length),'Assigned field coverage',Route,'purple'],['Secondary sales',money(sales),'This month · excluding GST',BarChart3,'orange']].map(([title,v,sub,Icon,tone]:any)=><section className="stat" key={title}><div className="stat-top"><span>{title}</span><span className={`stat-icon ${tone}`}><Icon size={20}/></span></div><strong>{v}</strong><small>{sub}</small></section>)}</div>
 <section className="panel management-actions"><div className="panel-heading"><h2>Management actions</h2><span className="subtle-pill">Admin only</span></div><div className="management-action-grid">{[['Doctors & customers','Customers',Stethoscope,'blue'],['Products & pricing','Products',Package,'purple'],['Create route','Routes',Route,'green'],['Allot samples','Samples',Gift,'orange']].map(([title,kind,Icon,tone]:any)=><button key={kind} onClick={()=>open(kind,null,kind==='Samples'?{Movement:'Issued to rep'}:{})}><span className={`quick-icon ${tone}`}><Icon size={23}/></span><b>{title}</b><Plus size={17}/></button>)}</div></section>
 <div className="management-alerts"><button onClick={()=>go('Orders')}><ShoppingBagIcon/><span><b>{ordersAwaiting} orders awaiting supply</b><small>Review stockist fulfilment</small></span><ChevronRight size={18}/></button><button onClick={()=>go('Expenses')}><span className="quick-icon orange"><Clock size={21}/></span><span><b>{expensesPending} expenses to review</b><small>Approve or reject MR submissions</small></span><ChevronRight size={18}/></button></div>
 <section className="panel"><div className="panel-heading"><h2>MR performance</h2><button className="text-button" onClick={()=>go('Performance')}>Detailed report<ChevronRight size={16}/></button></div>{performanceTable}</section><p className="footnote">{unassigned>0?`${unassigned} legacy or unassigned activity records this month are excluded from MR-wise totals. `:''}MR achievement uses secondary sales. Company totals can include unassigned sales.</p>
 </>;
 if(tab==='Performance')return <>{controls}<div className="stats">{[['Secondary sales',money(performance.reduce((a,p)=>a+p.sales,0))],['Combined target',money(performance.reduce((a,p)=>a+p.target,0))],['Recorded visits',String(performance.reduce((a,p)=>a+p.visits,0))],['Orders generated',money(performance.reduce((a,p)=>a+p.orders,0))]].map(([name,v])=><section className="stat" key={name}><div className="stat-top">{name}</div><strong>{v}</strong><small>Selected MRs · {month}</small></section>)}</div><section className="panel"><div className="panel-heading"><h2>Representative comparison</h2><button className="secondary" onClick={()=>csvDownload(['MR','District','Headquarters','Target','Secondary sales','Achievement %','Orders','Visits','Doctors covered','Working days','Expenses'],performance.map(p=>[p.m.name,p.m.district,p.m.headquarters,p.target,p.sales,p.percent.toFixed(1),p.orders,p.visits,p.doctors,p.days,p.expenses]),`MR-performance-${month}.csv`)}><Download size={17}/>Export</button></div>{performanceTable}<p className="footnote">Working days count distinct check-in dates. Sales exclude GST. Orders exclude cancelled entries. Expenses exclude rejected entries. Targets use month-specific settings when saved, otherwise the current MR profile target.</p></section></>;
 if(tab==='Locations')return <>{controls}<div className="location-explainer"><Navigation size={20}/><p>Last recorded GPS only. A new position appears when an MR captures location during a visit or attendance. This is not continuous live tracking.</p></div><div className="location-grid">{locations.map(({m,latest,history})=>{const gps=latest?parseGPS(latest.data.Location):null;const captured=latest?.data['Location captured at']||latest?.created;return <section className="panel location-card" key={m.email}><div className="rep-summary-head"><span className="avatar">{initials(m.name)}</span><div><b>{m.name}</b><small>{m.headquarters||m.district||'No headquarters'}</small></div><span className={`badge ${gps?'success':'amber'}`}>{gps?'Recorded':'No GPS'}</span></div>{gps&&latest?<><div className="coordinate-box"><MapPin size={24}/><div><b>{gps.lat.toFixed(5)}, {gps.lng.toFixed(5)}</b><small>{latest.kind}{latest.data.Customer?' · '+latest.data.Customer:''}</small></div></div><dl><div><dt>Captured</dt><dd>{new Date(captured).toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit',timeZone:'Asia/Kolkata'})}</dd></div><div><dt>Accuracy</dt><dd>{gps.accuracy===null?'Not recorded':`±${gps.accuracy} metres`}</dd></div><div><dt>Assigned route</dt><dd>{idList(m.route_ids).map(id=>rows.find(r=>r.id===id)?.data.Name).filter(Boolean).join(', ')||m.route||'Not assigned'}</dd></div></dl><a className="button secondary full-button" href={`https://www.google.com/maps?q=${gps.lat},${gps.lng}`} target="_blank" rel="noopener noreferrer"><ExternalLink size={16}/>Open recorded location</a><details><summary>Recent locations ({Math.min(history.length,5)})</summary>{history.slice(0,5).map(r=>{const p=parseGPS(r.data.Location)!;return <a key={r.id} href={`https://www.google.com/maps?q=${p.lat},${p.lng}`} target="_blank" rel="noopener noreferrer">{dateLabel(r.data['Location captured at']||r.created)} · {r.kind} · {p.lat.toFixed(4)}, {p.lng.toFixed(4)}<ExternalLink size={13}/></a>})}</details></>:<div className="empty-state"><MapPin size={30}/><h3>No location captured</h3><p>This MR has not saved a visit or attendance entry with GPS.</p></div>}</section>})}</div>{!locations.length&&<div className="empty-state"><Users size={30}/><h3>No representatives to show</h3><p>Add an MR or change your filters.</p></div>}</>;
 return <>{controls}<div className="activity-filter"><label>Activity type<select value={kindFilter} onChange={e=>setKindFilter(e.target.value)}><option value="">All activity</option>{activityKinds.map(k=><option key={k}>{k}</option>)}</select></label><span>{assignedActivity.length} records</span></div><section className="panel activity-timeline">{assignedActivity.map(r=>{const mr=filteredReps.find(m=>attributed(r,m));return <button key={r.id} className="admin-activity-row" onClick={()=>open(r.kind,r)}><span className="avatar">{initials(mr?.name||'MR')}</span><span className="activity-content"><b>{mr?.name} <span>· {r.kind}</span></b><small>{r.data.Customer||r.data.Product||r.data.Category||r.data.Action||r.data.Purpose||'Activity recorded'}{r.data.Route?' · '+r.data.Route:''}</small><small>{dateLabel(r.data.Date||r.created)}{r.data.Time?' · '+r.data.Time:''}</small></span>{r.data.Status&&<span className="badge blue">{r.data.Status}</span>}<ChevronRight size={18}/></button>})}{!assignedActivity.length&&<div className="empty-state large"><Activity size={32}/><h3>No activity in this selection</h3><p>MR visits, attendance and submissions appear here as they are recorded.</p></div>}</section></>;
}
function ShoppingBagIcon(){return <span className="quick-icon blue"><Package size={21}/></span>}
