'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Plus,RefreshCw,Gift,Package,Pencil} from 'lucide-react';
import {money,type FieldRecord} from '../lib/ui-config';
import type {Member} from '../lib/permissions';
import {captureGPS} from '../lib/field-rules';
import {AllotmentRequests} from './mr-improvements';
import {request,Sheet,ErrorNote,GPSNote} from './field-ui';
export function BenefitsPanel({kind,rows,team,admin,refresh,editGift}:{kind:'gift'|'sample';rows:FieldRecord[];team:Member[];admin:boolean;refresh:()=>Promise<void>;editGift:(row:FieldRecord|null)=>void}){
 const [data,setData]=useState<any>({balances:[],movements:[],supplied:[],totals:[]}),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mr,setMR]=useState(''),[itemId,setItem]=useState(''),[qty,setQty]=useState(1),[cost,setCost]=useState(0),[customerId,setCustomer]=useState(''),[requestId,setRequestId]=useState(''),[movement,setMovement]=useState<'allocate'|'return'>('allocate');
 const items=rows.filter(r=>r.kind===(kind==='gift'?'Gifts':'Products')),customers=rows.filter(r=>r.kind==='Customers'),name=(id:string)=>rows.find(r=>r.id===id)?.data.Name||'Historical item',item=items.find(r=>r.id===itemId);
 async function load(){try{setData(await request('/api/benefits'));setError('')}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 function start(){setMovement('allocate');setRequestId(crypto.randomUUID());setMR('');setItem('');setQty(1);setCost(0);setCustomer('');setError('');setShow(true)}
 const already=kind==='gift'&&data.supplied.some((s:any)=>s.item_id===itemId&&s.customer_id===customerId),blocked=already&&item?.data['One per customer']!=='No';
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const gps=admin?undefined:await captureGPS();await request('/api/benefits',{id:requestId,kind,movement:admin?movement:'issue',mrEmail:mr,itemId,qty,unitCost:cost,customerId,gps});setShow(false);await load();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const balances=data.balances.filter((b:any)=>b.kind===kind&&(!mr||b.mr_email===mr)),movements=data.movements.filter((b:any)=>b.kind===kind&&(!mr||b.mr_email===mr));
 return <div className="workflow-panel"><div className="workflow-toolbar"><div><h2>{kind==='gift'?'Gifts & complimentary materials':'Sample stock & utilisation'}</h2><p>{admin?'Allot quantities and costs to each MR.':'Record customer distribution from your allotted stock.'}</p></div><button className="icon-button" onClick={load} aria-label="Refresh balances"><RefreshCw size={18}/></button>{admin&&kind==='gift'&&<button className="secondary" onClick={()=>editGift(null)}>Add gift material</button>}<button className="primary" onClick={start}><Plus size={18}/>{admin?'Allot stock':'Issue to customer'}</button></div><ErrorNote error={show?'':error}/>{admin&&<label className="inline-filter">Representative<select value={mr} onChange={e=>setMR(e.target.value)}><option value="">All MRs</option>{team.filter(m=>m.role==='mr').map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select></label>}
 <AllotmentRequests kind={kind} rows={rows} team={team} admin={admin} balances={data.balances} changed={async()=>{await load();await refresh()}}/><div className="stats"><section className="stat"><span>Available units</span><strong>{balances.reduce((n:number,b:any)=>n+b.quantity,0)}</strong></section><section className="stat"><span>Available stock cost</span><strong>{money(balances.reduce((n:number,b:any)=>n+b.value,0)/100)}</strong></section><section className="stat"><span>Distributed cost</span><strong>{money(data.totals.filter((m:any)=>m.kind===kind&&m.movement==='issue'&&(!mr||m.mr_email===mr)).reduce((n:number,m:any)=>n-m.cost,0)/100)}</strong></section></div>
 {admin&&kind==='gift'&&<div className="stock-grid">{items.map(i=><section className="panel stock-card" key={i.id}><h3><Gift size={20}/>{i.data.Name}</h3><p>Cost {money(Number(i.data['Unit cost']||0))} · {i.data['One per customer']==='No'?'Repeat supply allowed':'One supply per customer'}</p><button className="secondary" onClick={()=>editGift(i)}><Pencil size={16}/>Edit material & rule</button></section>)}</div>}
 <section className="panel ledger-list"><h3>Allotted stock remaining</h3>{balances.map((b:any)=><div className="balance-line" key={b.id}><span><b>{name(b.item_id)}</b>{admin&&<small>{team.find(m=>m.email===b.mr_email)?.name||b.mr_email}</small>}</span><strong>{b.quantity} units · {money(b.value/100)}</strong></div>)}{!balances.length&&<p>No allotments yet.</p>}</section><section className="panel ledger-list"><h3>Distribution & allotment history</h3><p>Latest 2,000 entries; balances and cost totals include all entries.</p>{movements.map((m:any)=><div className="balance-line" key={m.id}><span><b>{name(m.item_id)} · {m.movement==='allocate'?'Allotted':m.movement==='return'?'Returned unused stock':`Issued to ${name(m.customer_id)}`}</b><small>{new Date(m.created).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}{admin?` · ${team.find(r=>r.email===m.mr_email)?.name||m.mr_email}`:''}</small>{m.gps&&<a href={`https://www.google.com/maps?q=${JSON.parse(m.gps).lat},${JSON.parse(m.gps).lng}`} target="_blank" rel="noopener noreferrer">Recorded GPS</a>}</span><strong>{Math.abs(m.quantity)} units · {money(Math.abs(m.cost)/100)}</strong></div>)}</section>
 {show&&<Sheet title={admin?`${movement==='return'?'Return':'Allot'} ${kind} stock`:`Issue ${kind} to customer`} close={()=>setShow(false)} busy={busy}><form onSubmit={save}><div className="form-grid">{admin&&<label>Movement<select value={movement} onChange={e=>setMovement(e.target.value as 'allocate'|'return')}><option value="allocate">Allot stock</option><option value="return">Return unused stock</option></select></label>}{admin&&<label>MR<select required value={mr} onChange={e=>setMR(e.target.value)}><option value="">Select MR</option>{team.filter(m=>m.role==='mr'&&(movement==='return'||m.status==='active')).map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select></label>}<label>{kind==='gift'?'Gift material':'Sample product'}<select required value={itemId} onChange={e=>{setItem(e.target.value);const item=items.find(i=>i.id===e.target.value);setCost(Number(item?.data[kind==='gift'?'Unit cost':'Sample cost']||0))}}><option value="">Select item</option>{items.filter(i=>admin||data.balances.some((b:any)=>b.item_id===i.id&&b.kind===kind&&b.quantity>0)).map(i=><option key={i.id} value={i.id}>{i.data.Name}</option>)}</select></label><label>Quantity<input type="number" min="1" max="100000" required value={qty} onChange={e=>setQty(Number(e.target.value))}/></label>{admin?(movement==='allocate'?<label>Cost per unit (₹)<input type="number" min="0" step="0.01" required value={cost} onChange={e=>setCost(Number(e.target.value))}/></label>:null):<label>Customer<select required value={customerId} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.data.Name} · {c.data.Route}</option>)}</select></label>}</div>{already&&<div className={blocked?'form-error':'info-box'}>Already supplied to this customer.{blocked?' Admin’s one-supply rule blocks another issue.':' Repeat supply is currently allowed by Admin.'}</div>}{!admin&&<GPSNote/>}<ErrorNote error={error}/><div className="dialog-actions"><button type="button" className="secondary" onClick={()=>setShow(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy||blocked}>{busy?'Saving…':admin?(movement==='return'?'Record return':'Allot stock'):'Capture GPS & issue'}</button></div></form></Sheet>}
 </div>
}
