'use client';
import {useEffect,useState,useRef} from 'react';
import {ReportSection} from './report-table';
import {reportStyles,printReport} from '../lib/report-print';
import {Printer,RefreshCw,Target} from 'lucide-react';
import {request,ErrorNote} from './field-ui';
import {shiftMonth} from '../lib/route-insights';
import {today} from '../lib/ui-config';
import {rupees,type buildReport} from '../lib/monthly-report';
import type {Member} from '../lib/permissions';
type Summary={email:string;name:string;target:number;achieved:number;pending:number;exceeded:number;percentage:number;targetSaved:boolean};
type Report=ReturnType<typeof buildReport>&{closed?:boolean;closedAt?:string};
function TargetCards({s}:{s:Summary}){return <div className="target-cards">{[['Monthly target',rupees(s.target)],['Achieved sales',rupees(s.achieved)],['Achievement',s.percentage.toFixed(1)+'%'],['Pending target',rupees(s.pending)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}<div className="target-bar"><i style={{width:Math.min(100,Math.max(0,s.percentage))+'%'}}/></div>{s.exceeded>0&&<p>Target exceeded by {rupees(s.exceeded)}</p>}</div>}
export function MonthlyTargets({revision}:{revision?:unknown}){
 const [data,setData]=useState<Summary[]>([]),[error,setError]=useState(''),[month,setMonth]=useState(today().slice(0,7));
 useEffect(()=>{let live=true;setData([]);request<{summaries:Summary[]}>(`/api/monthly-report?summary=1&month=${month}`).then(d=>{if(live){setData(d.summaries);setError('')}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[month,revision]);
 const all={email:'',name:'',target:data.reduce((n,s)=>n+s.target,0),achieved:data.reduce((n,s)=>n+s.achieved,0),pending:data.reduce((n,s)=>n+s.pending,0),exceeded:0,percentage:0,targetSaved:false};all.percentage=all.target?all.achieved/all.target*100:0;
 return <section className="panel monthly-target-panel"><div className="panel-heading"><h2><Target size={20}/>Monthly target performance</h2><input aria-label="Target performance month" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></div><ErrorNote error={error}/>{data.length>0?<><TargetCards s={data.length===1?data[0]:all}/>{data.length>1&&<div className="report-scroll"><table><thead><tr><th>MR</th><th>Target</th><th>Achieved</th><th>Achievement</th><th>Pending</th></tr></thead><tbody>{data.map(s=><tr key={s.email}><td>{s.name}</td><td>{rupees(s.target)}</td><td>{rupees(s.achieved)}</td><td>{s.percentage.toFixed(1)}%</td><td>{rupees(s.pending)}</td></tr>)}</tbody></table></div>}<p className="footnote">Delivered secondary sales excluding GST. Pending is calculated per MR. Set month-specific targets in Reports; otherwise the current MR profile target applies.</p></>:!error&&<p className="empty-inline">No target data loaded.</p>}</section>
}
export function MonthlyReport({user,team,onSaved,initialMonth}:{user:Member;team:Member[];onSaved:()=>Promise<void>;initialMonth?:string}){
 const report=useRef<HTMLElement>(null);
 const admin=user.role==='admin',reps=admin?team.filter(m=>m.role==='mr'):[user];
 const [month,setMonth]=useState(initialMonth||today().slice(0,7)),[email,setEmail]=useState(admin?'':user.email),[data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[target,setTarget]=useState(''),[revision,setRevision]=useState(0),[compare,setCompare]=useState(shiftMonth(today().slice(0,7),-1)),[inactive,setInactive]=useState(3),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!email&&reps.length)setEmail(reps[0].email)},[email,reps]);
 useEffect(()=>{let live=true;setData(null);setError('');if(!email)return;setBusy(true);request<Report>(`/api/monthly-report?month=${month}&mr=${encodeURIComponent(email)}&compare=${compare}&inactive=${inactive}`).then(d=>{if(live){setData(d);setTarget(String(d.summary.target/100))}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[month,email,revision,compare,inactive]);
 async function saveTarget(){setSaving(true);try{await request('/api/monthly-report',{month,email,target:Number(target)});setRevision(n=>n+1);await onSaved()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function print(){if(data&&report.current)try{await printReport(report.current,`VETMECH-${data.member.name}-${data.month}-Monthly-Report`)}catch(e){setError((e as Error).message)}}
 return <div className="reports-workspace"><style>{reportStyles}</style><section className="panel report-controls"><div className="admin-filters"><label>Report month<input type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setCompare(shiftMonth(e.target.value,-1))}}}/></label><label>Compare with<input disabled={!!data?.closed} type="month" value={compare} onChange={e=>{if(e.target.value)setCompare(e.target.value)}}/></label><label>No orders for previous<select disabled={!!data?.closed} value={inactive} onChange={e=>setInactive(Number(e.target.value))}>{[1,2,3,6,12].map(n=><option key={n} value={n}>{n} complete month{n>1?'s':''}</option>)}</select></label><label>Representative<select value={email} onChange={e=>setEmail(e.target.value)}><option value="">Select MR</option>{reps.map(m=><option value={m.email} key={m.email}>{m.name}{m.status==='disabled'?' (disabled)':''}</option>)}</select></label><button className="secondary" onClick={()=>setRevision(n=>n+1)} disabled={busy}><RefreshCw size={17}/>Refresh</button><button className="primary" onClick={print} disabled={!data||busy}><Printer size={18}/>Print / Save PDF</button></div><p className="footnote">Print the complete report as one document. Choose “Save as PDF” in your device’s print window. The report uses colour-coded sections and landscape A4 pages. Keep colour / background graphics enabled in the print settings.</p>{admin&&data&&!data.closed&&<div className="monthly-target-edit"><label>Target for {month} (₹)<input type="number" min="1" max="100000000" value={target} onChange={e=>setTarget(e.target.value)}/></label><button className="secondary" disabled={saving||busy} onClick={saveTarget}>{saving?'Saving…':'Save monthly target'}</button><span>{data.summary.targetSaved?'Month-specific target saved':'Using current MR profile target'}</span></div>}<ErrorNote error={error}/>{busy&&<p>Preparing the complete monthly report…</p>}{!email&&<p>Create or select an MR to generate a report.</p>}</section>
 {data&&<article ref={report} className="monthly-report"><div className="report-summary"><header className="report-cover"><div><span className="eyebrow">VETMECH PHARMACEUTICALS PRIVATE LIMITED</span><h2>MR monthly business report</h2>{data.closed&&<p className="closed-report-banner">APPROVED & LOCKED · {new Date(data.closedAt!).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST<br/>This is the saved month-end report. Its comparison settings and figures are preserved.</p>}<h3>{data.member.name} · {data.month}</h3><p>Employee: {data.member.employeeCode||'—'} · Phone: {data.member.phone||'—'} · HQ: {data.member.headquarters||'—'}</p><p>Districts: {data.member.districts||'—'} · Routes: {data.member.routes||'—'}</p><p>Territory: {data.member.territory||'—'}</p><small>Generated {new Date(data.generated).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</small></div></header><TargetCards s={data.summary}/><p className="report-note">Achievement = delivered secondary net sales ÷ target × 100. GST is excluded. {data.summary.targetSaved?'Uses the saved target for this month.':'Uses the current profile target; Admin can save a month-specific target.'}</p><div className="report-metrics">{[['Visits',data.metrics.visits],['Customers visited',data.metrics.customersVisited],['Repeat visits',data.metrics.repeatVisits],['Secondary orders',data.metrics.orders],['Days checked in',data.metrics.workingDays],['Agency primary sales excl. GST',rupees(data.metrics.primary)],['Samples / gifts issued cost',rupees(data.metrics.benefitCost)]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="report-note">Agency stock covers the app’s invoice ledger only. Shared agency primary sales are not individual MR achievement. Customer issued quantities do not measure customer consumption or remaining stock. No records are truncated to a recent-activity limit.</p>
 </div>{data.tables.map((t,index)=><ReportSection key={t.title} table={t} index={index}/>)}<footer className="report-end">End of report · {data.member.name} · {data.month} · Confidential company review</footer></article>}</div>
}
