'use client';
import {useEffect,useState,useRef} from 'react';
import {ReportSection} from './report-table';
import {reportStyles,printReport} from '../lib/report-print';
import {Printer,RefreshCw} from 'lucide-react';
import {request,ErrorNote} from './field-ui';
import {today} from '../lib/ui-config';
import {shiftMonth,type routeInsights} from '../lib/route-insights';
import type {Member} from '../lib/permissions';
export function RoutePerformance({user,team}:{user:Member;team:Member[]}){
 const report=useRef<HTMLElement>(null);
 const reps=user.role==='admin'?team.filter(m=>m.role==='mr'):[user], [email,setEmail]=useState(user.role==='admin'?'':user.email),[month,setMonth]=useState(today().slice(0,7)),[compare,setCompare]=useState(shiftMonth(today().slice(0,7),-1)),[inactive,setInactive]=useState(3),[route,setRoute]=useState(''),[data,setData]=useState<ReturnType<typeof routeInsights>|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!email&&reps.length)setEmail(reps[0].email)},[email,reps]);
 useEffect(()=>{let live=true;setData(null);setError('');if(!email)return;setBusy(true);request<ReturnType<typeof routeInsights>>(`/api/route-performance?mr=${encodeURIComponent(email)}&month=${month}&compare=${compare}&inactive=${inactive}`).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[email,month,compare,inactive,revision]);
 return <div className="reports-workspace"><style>{reportStyles}</style><section className="panel report-controls"><div className="admin-filters"><label>MR<select value={email} onChange={e=>{setEmail(e.target.value);setRoute('')}}><option value="">Select MR</option>{reps.map(m=><option key={m.email} value={m.email}>{m.name}</option>)}</select></label><label>Month<input type="month" value={month} onChange={e=>{if(e.target.value){setMonth(e.target.value);setCompare(shiftMonth(e.target.value,-1))}}}/></label><label>Compare with<input type="month" value={compare} onChange={e=>{if(e.target.value)setCompare(e.target.value)}}/></label><label>No orders for previous<select value={inactive} onChange={e=>setInactive(Number(e.target.value))}>{[1,2,3,6,12].map(n=><option key={n} value={n}>{n} complete month{n>1?'s':''}</option>)}</select></label><label>Route<select value={route} onChange={e=>setRoute(e.target.value)}><option value="">All routes</option>{data?.tables[0].rows.map(r=><option key={r[0]} value={r[0]}>{r[0]}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={17}/>Refresh</button><button className="primary" disabled={!data||busy} onClick={()=>report.current&&printReport(report.current,`VETMECH-Route-${data?.mr}-${month}`).catch(e=>setError(e.message))}><Printer size={17}/>Print / Save PDF</button></div><ErrorNote error={error}/>{busy&&<p>Preparing route comparison and customer follow-up lists…</p>}<p className="footnote">Choose any two months. Inactivity checks the previous complete months and the selected month; customers with no order history are listed separately.</p></section>{data&&<article ref={report} className="monthly-report route-report"><header className="report-cover"><span className="eyebrow">VETMECH · COMPANY REVIEW</span><h2>Route performance & customer follow-up</h2><h3>{data.mr} · {month} versus {compare}</h3><p>{route||'All routes'} · Previous {inactive} complete months without orders</p></header>{data.tables.map((t,idx)=>{const filtered=t.rows.filter(r=>!route||(idx===0?r[0]:r[1])===route);return <ReportSection key={t.title} table={{...t,rows:filtered}} index={idx}/>})}<footer className="report-end">Generated {new Date().toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · Confidential company review</footer></article>}</div>
}
