'use client';
import {useState} from 'react';
import type {FieldRecord} from '../lib/ui-config';
type Selection={route_ids:string[];district_ids:string[];stockist_ids:string[]};
export function TerritoryFields({value,onChange,rows}:{value:Selection;onChange:(next:Selection)=>void;rows:FieldRecord[]}){
 const [filter,setFilter]=useState('');const routes=rows.filter(r=>r.kind==='Routes'),districts=rows.filter(r=>r.kind==='Districts'),stocks=rows.filter(r=>r.kind==='Stockists');
 const implied=districts.filter(d=>routes.some(r=>value.route_ids.includes(r.id)&&r.data.District===d.data.Name)).map(d=>d.id);
 const toggle=(key:keyof Selection,id:string,checked:boolean)=>onChange({...value,[key]:checked?[...value[key],id]:value[key].filter(v=>v!==id)});
 return <section className="full-field territory-fields"><h3>Routes, districts & stockists</h3><p>Select the precise routes covered by this MR. Shared routes and stockists can be assigned to multiple MRs.</p><input aria-label="Find a route" placeholder="Search route or district…" value={filter} onChange={e=>setFilter(e.target.value)}/><div className="check-grid">{routes.filter(r=>`${r.data.Name} ${r.data.District}`.toLowerCase().includes(filter.toLowerCase())).map(r=><label key={r.id}><input type="checkbox" checked={value.route_ids.includes(r.id)} onChange={e=>toggle('route_ids',r.id,e.target.checked)}/><span><b>{r.data.Name}</b><small>{r.data.District}</small></span></label>)}</div><h4>Districts</h4><p>Districts containing the selected routes are included automatically. District assignment alone does not grant all routes.</p><div className="check-grid">{districts.map(r=><label key={r.id}><input type="checkbox" disabled={implied.includes(r.id)} checked={implied.includes(r.id)||value.district_ids.includes(r.id)} onChange={e=>toggle('district_ids',r.id,e.target.checked)}/><span>{r.data.Name}{implied.includes(r.id)&&<small>From selected route</small>}</span></label>)}</div><h4>Supplying stockists</h4><div className="check-grid">{stocks.map(r=><label key={r.id}><input type="checkbox" checked={value.stockist_ids.includes(r.id)} onChange={e=>toggle('stockist_ids',r.id,e.target.checked)}/><span>{r.data.Name}<small>{r.data.District}</small></span></label>)}</div>{!routes.length&&<p>Add districts and routes before assigning territory.</p>}</section>
}
