'use client';
import {useEffect,useRef,useState} from 'react';

type Entry={id:string;kind:string;revision:number;content:string;saved:string;stopped:boolean;queue:Promise<unknown>};
export function useDraft(id:string,kind:string,payload:unknown,enabled:boolean,initialRevision=0){const entries=useRef(new Map<string,Entry>()),[status,setStatus]=useState('');const content=JSON.stringify(payload);let entry=entries.current.get(id);if(id&&!entry&&enabled){entry={id,kind,revision:initialRevision,content,saved:initialRevision?content:'',stopped:false,queue:Promise.resolve()};entries.current.set(id,entry)}if(entry&&enabled){entry.content=content;if(initialRevision>entry.revision){entry.revision=initialRevision;entry.saved=content;}}
 function save(e=entry){if(!e||e.stopped)return Promise.resolve();const job=e.queue.catch(()=>{}).then(async()=>{if(e.stopped||e.saved===e.content)return;const value=e.content;setStatus('Saving draft…');const response=await fetch('/api/drafts',{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({id:e.id,kind:e.kind,revision:e.revision,payload:JSON.parse(value)})});const r=await response.json() as any;if(!response.ok)throw new Error(r.error||'Unable to save draft.');e.revision=r.revision;e.saved=value;setStatus('Draft saved');});e.queue=job;job.catch(err=>setStatus('Draft not saved: '+err.message));return job;}
 useEffect(()=>{if(!enabled||!entry)return;const timer=setTimeout(()=>{save(entry).catch(()=>{})},800);return()=>clearTimeout(timer)},[id,content,enabled]);
 useEffect(()=>{const flush=()=>{for(const e of entries.current.values())if(!e.stopped)save(e).catch(()=>{})};const hidden=()=>{if(document.visibilityState==='hidden')flush()};const warn=(event:BeforeUnloadEvent)=>{if([...entries.current.values()].some(e=>!e.stopped&&e.saved!==e.content)){event.preventDefault();event.returnValue='';flush()}};document.addEventListener('visibilitychange',hidden);window.addEventListener('beforeunload',warn);return()=>{document.removeEventListener('visibilitychange',hidden);window.removeEventListener('beforeunload',warn);flush()}},[]);
 return {status,save:()=>save(),complete:()=>{if(entry)entry.stopped=true},revision:()=>entry?.revision||0};
}
