'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Trash2,Plus} from 'lucide-react';
import type {FieldRecord} from '../lib/ui-config';
import {captureGPS} from '../lib/field-rules';
import {request,Sheet,ErrorNote,GPSNote} from './field-ui';
import {useDraft} from './use-draft';
import {CommercePanel} from './commerce-panel';
type Issue={itemId:string;qty:number;commitmentId?:string};
export function VisitClose({visit,rows,close,refresh}:{visit:FieldRecord;rows:FieldRecord[];close:()=>void;refresh:()=>Promise<void>}){
 const [benefits,setBenefits]=useState<any>({balances:[],supplied:[]}),[commitments,setCommitments]=useState<any[]>([]),[gifts,setGifts]=useState<Issue[]>([]),[samples,setSamples]=useState<Issue[]>([]),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[orderPanel,setOrderPanel]=useState(false);
 const customerId=visit.data['Customer ID'];
 const [draftId,setDraftId]=useState(''),[draftRevision,setDraftRevision]=useState(0);
 const draft=useDraft(draftId,'visit_close',{visitId:visit.id,customerName:visit.data.Customer,gifts,samples,notes},!!draftId&&!busy,draftRevision);
 useEffect(()=>{let active=true;request('/api/drafts').then(d=>{if(!active)return;const saved=d.drafts.find((x:any)=>x.kind==='visit_close'&&x.payload.visitId===visit.id);if(saved){setGifts(saved.payload.gifts||[]);setSamples(saved.payload.samples||[]);setNotes(saved.payload.notes||'');setDraftRevision(saved.revision);setDraftId(saved.id)}else setDraftId(crypto.randomUUID())}).catch(e=>setError(e.message));return()=>{active=false}},[visit.id]);
 function keep(){draft.save().then(close).catch(e=>setError(e.message))}
 async function load(){try{const [b,c]=await Promise.all([request('/api/benefits'),request('/api/commerce')]);setBenefits(b);setCommitments(c.commitments.filter((p:any)=>p.customer_id===customerId))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[]);
 const name=(id:string)=>rows.find(r=>r.id===id)?.data.Name||'Item';
 function editors(kind:'gift'|'sample',items:Issue[],setItems:(next:Issue[])=>void){return <section className="visit-benefits"><h3>{kind==='gift'?'Gifts issued on this visit':'Samples issued on this visit'}</h3>{items.map((i,n)=>{const material=rows.find(r=>r.id===i.itemId),already=kind==='gift'&&benefits.supplied.some((s:any)=>s.customer_id===customerId&&s.item_id===i.itemId),blocked=already&&material?.data['One per customer']!=='No';return <div className="invoice-line-editor" key={n}><label>Item<select required value={i.itemId} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,itemId:e.target.value,commitmentId:undefined}:x))}><option value="">Select item</option>{benefits.balances.filter((b:any)=>b.kind===kind&&b.quantity>0).map((b:any)=><option key={b.id} value={b.item_id}>{name(b.item_id)} · Available {b.quantity}</option>)}</select></label><label>Quantity<input type="number" required min="1" max="10000" value={i.qty} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,qty:Number(e.target.value)}:x))}/></label>{kind==='sample'&&<label>Fulfil commitment<select value={i.commitmentId||''} onChange={e=>setItems(items.map((x,k)=>k===n?{...x,commitmentId:e.target.value||undefined}:x))}><option value="">Regular sample issue</option>{commitments.filter(c=>c.product_id===i.itemId).map(c=><option key={c.id} value={c.id}>{c.quantity-c.fulfilled} pending · {c.notes||'Order commitment'}</option>)}</select></label>}<button type="button" className="icon-button" aria-label="Remove item" onClick={()=>setItems(items.filter((_,k)=>k!==n))}><Trash2 size={18}/></button>{already&&<p className={blocked?'form-error':'field-help'}>Already supplied.{blocked?' Another issue is blocked.':' Repeat issue is allowed by Admin.'}</p>}</div>})}<button type="button" className="secondary" disabled={items.length>=10} onClick={()=>setItems([...items,{itemId:'',qty:1}])}><Plus size={16}/>Add {kind}</button></section>}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await draft.save();const gps=await captureGPS();await request('/api/visits/close',{id:visit.id,gps,gifts,samples,notes});draft.complete();await refresh();close()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Sheet title={`Close visit · ${visit.data.Customer}`} close={keep} busy={busy}><p>Record any order, gifts or samples before closing this visit.</p><button className="secondary" type="button" onClick={()=>setOrderPanel(!orderPanel)}>{orderPanel?'Hide orders':'Take / review order'}</button>{orderPanel&&<CommercePanel tab="Orders" rows={rows} admin={false} refresh={refresh} initialCustomer={customerId} initialVisit={visit.id} onSaved={load}/>}<form onSubmit={save}><p className="draft-status" role="status">{draft.status||'Loading saved visit notes…'}</p>{commitments.length>0&&<div className="info-box"><div><b>Outstanding sample commitments</b>{commitments.map(c=><p key={c.id}>{name(c.product_id)}: {c.quantity-c.fulfilled} remaining{c.notes?` · ${c.notes}`:''}</p>)}</div></div>}{editors('gift',gifts,setGifts)}{editors('sample',samples,setSamples)}<label className="workflow-notes">Closing notes<textarea maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><GPSNote/><p className="field-help">A thank-you message, including this visit’s orders, is queued for WhatsApp. Delivery status is available in the WhatsApp menu.</p><ErrorNote error={error}/><div className="dialog-actions"><button type="button" className="secondary" onClick={keep} disabled={busy}>Save draft & keep visit open</button><button className="primary" disabled={busy||!draftId}>{busy?'Capturing GPS & closing…':'Issue items & close visit'}</button></div></form></Sheet>
}
