import {canRead,type Member} from './permissions';
import {idList} from './field-rules';
import {totals,owned,type Row} from './monthly-report';
import {shiftMonth} from './route-insights';
export function comparison(m:Member,month:string,records:Row[],invoices:Row[],benefits:Row[],archive?:any){
 const visits=records.filter(r=>r.kind==='Visits'&&owned(r,m)&&(r.data.Date||r.created).startsWith(month)),customerKey=(r:Row)=>r.data['Customer ID']||r.data.Customer;
 const delivered=invoices.filter(i=>i.kind==='secondary'&&i.status==='Delivered'&&i.mr_email===m.email&&i.date.startsWith(month));
 const usage=benefits.filter(b=>b.mr_email===m.email&&b.movement==='issue'&&new Date(b.created).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}).startsWith(month));
 const result={...totals(m,month,records,invoices),districts:[...new Set([...idList(m.district_ids).map(id=>records.find(r=>r.id===id)?.data.Name).filter(Boolean),...(m.district?[m.district]:[])])],headquarters:m.headquarters,visits:visits.length,repeatVisits:visits.length-new Set(visits.map(customerKey)).size,orderingCustomers:new Set(delivered.map(i=>i.customer_id)).size,sampleCost:usage.filter(b=>b.kind==='sample').reduce((n,b)=>n-b.cost,0),giftCost:usage.filter(b=>b.kind==='gift').reduce((n,b)=>n-b.cost,0),closed:!!archive};
 if(archive){Object.assign(result,archive.summary,{visits:archive.metrics.visits,repeatVisits:archive.metrics.repeatVisits,orderingCustomers:archive.tables.find((t:any)=>t.title==='Highest order-value customers')?.rows.length||0});const amounts=archive.tables.find((t:any)=>t.title==='Samples and gifts — allocation, usage and closing balance')?.rows||[];const cost=(kind:string)=>amounts.filter((r:any)=>r[0]===kind).reduce((n:number,r:any)=>n+Math.round(Number(String(r[7]).replace(/[^\d.-]/g,''))*100),0);result.sampleCost=cost('sample');result.giftCost=cost('gift');}
 return result;
}
export function overdueActions(today:string,reps:Member[],records:Row[],tasks:Row[]){const result:Row[]=[];const customer=(mr:Member,id:string)=>{const r=records.find(r=>r.id===id&&r.kind==='Customers');return r&&canRead(mr,{...r,data:JSON.stringify(r.data)} as any)?r:null};
 for(const m of reps){const saved=tasks.filter(t=>t.mr_email===m.email);for(const t of saved.filter(t=>t.status==='Open'&&t.due<today)){const c=customer(m,t.customer_id);if(c)result.push({...t,mr:m.name,customer:c.data.Name,route:c.data.Route,title:t.source.startsWith('sample:')?'Sample commitment':'Scheduled follow-up'})}
 const visits=records.filter(r=>r.kind==='Visits'&&owned(r,m)).sort((a,b)=>(b.data.Date||b.created).localeCompare(a.data.Date||a.created)||b.created.localeCompare(a.created)),seen=new Set();for(const v of visits){const id=v.data['Customer ID']||records.find(c=>c.kind==='Customers'&&c.data.Name===v.data.Customer)?.id;if(!id||seen.has(id))continue;seen.add(id);if(saved.some(t=>t.source==='visit:'+v.id))continue;const c=customer(m,id);if(c&&v.data['Follow-up date']&&v.data['Follow-up date']<today)result.push({id:'visit:'+v.id,mr_email:m.email,mr:m.name,customer:c.data.Name,customer_id:id,route:c.data.Route,due:v.data['Follow-up date'],title:'Visit due',notes:v.data.Response||''})}}
 return result.sort((a,b)=>a.due.localeCompare(b.due));
}
export function pendingMonths(today:string,records:Row[],invoices:Row[],locks:Row[]){const dates=[...records.map(r=>r.data.Date),...invoices.map(i=>i.date)].filter((d):d is string=>typeof d==='string'&&/^20\d{2}-(0[1-9]|1[0-2])-\d{2}$/.test(d)).sort();if(!dates.length)return [];const result=[];let month=dates[0].slice(0,7);while(month<today.slice(0,7)){if(!locks.some(l=>l.month===month&&l.closed))result.push({month,placed:invoices.filter(i=>i.kind==='secondary'&&i.status==='Placed'&&i.date.slice(0,7)<=month).length});month=shiftMonth(month,1)}return result;}
