import type {Member} from './permissions';
type Row=Record<string,any>;
export function recordedGPS(data:Record<string,string>,day:string){try{const p=JSON.parse(data['GPS data']||'null');if(!p||!Number.isFinite(p.lat)||p.lat<-90||p.lat>90||!Number.isFinite(p.lng)||p.lng<-180||p.lng>180||!Number.isFinite(p.accuracy)||p.accuracy<0||!Number.isFinite(Date.parse(p.capturedAt)))return null;if(new Date(p.capturedAt).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})!==day)return null;return {lat:p.lat as number,lng:p.lng as number,accuracy:p.accuracy as number,capturedAt:p.capturedAt as string}}catch{return null}}
export function attendanceMonth(m:Member,month:string,records:Row[],today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})){
 const [year,mon]=month.split('-').map(Number),count=new Date(Date.UTC(year,mon,0)).getUTCDate();const own=records.filter(r=>r.kind==='Attendance'&&(r.assigned_to?r.assigned_to===m.email:!!m.user_id&&r.owner===m.user_id));
 const days=Array.from({length:count},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),entries=own.filter(r=>r.data.Date===date).sort((a,b)=>a.created.localeCompare(b.created)),ins=entries.filter(r=>r.data.Action==='Check in'),outs=entries.filter(r=>r.data.Action==='Check out'),checkin=ins[0],checkout=outs.at(-1),inGPS=checkin?recordedGPS(checkin.data,date):null,outGPS=checkout?recordedGPS(checkout.data,date):null;let status='complete',label='Complete · GPS verified';if(date>today){status=entries.length?'review':'future';label=entries.length?'Future-dated record':'Upcoming'}else if(!checkin&&!checkout){status='missing';label='No check-in / checkout'}else if(!checkin){status='partial';label='Missing check-in'}else if(!checkout){status='partial';label=date===today?'Checkout pending':'Missing checkout'}else if(ins.length!==1||outs.length!==1){status='review';label='Duplicate entries - review'}else if(!inGPS||!outGPS){status='gps_missing';label='GPS missing / invalid'}else if(Date.parse(outGPS.capturedAt)<Date.parse(inGPS.capturedAt)){status='review';label='Checkout before check-in'}
 const minutes=status==='complete'?Math.round((Date.parse(outGPS!.capturedAt)-Date.parse(inGPS!.capturedAt))/60000):null,time=(r:Row|undefined,g:ReturnType<typeof recordedGPS>)=>g?new Date(g.capturedAt).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}):r?.data.Time||'—';
 return {date,day:i+1,weekday:new Date(date+'T12:00:00Z').toLocaleDateString('en-IN',{weekday:'short',timeZone:'Asia/Kolkata'}),status,label,checkin:time(checkin,inGPS),checkout:time(checkout,outGPS),inGPS,outGPS,duration:minutes===null?'—':`${Math.floor(minutes/60)}h ${minutes%60}m`,notes:entries.map(r=>r.data.Notes).filter(Boolean).join(' · '),entries:entries.length};});
 return {email:m.email,name:m.name,employeeCode:m.employee_code,district:m.district,month,days,summary:{complete:days.filter(d=>d.status==='complete').length,missing:days.filter(d=>d.status==='missing').length,incomplete:days.filter(d=>['partial','gps_missing','review'].includes(d.status)).length,upcoming:days.filter(d=>d.status==='future').length,elapsed:days.filter(d=>d.date<=today).length}};
}
export type AttendanceMonth=ReturnType<typeof attendanceMonth>;

export function attendanceShortLabel(d:AttendanceMonth['days'][number]){return d.status==='complete'?'Complete + GPS':d.status==='missing'?'No entries':d.status==='partial'?(d.label==='Missing check-in'?'Missing check-in':'Checkout pending'):d.status==='gps_missing'?'GPS missing':d.status==='review'?'Review entries':'Upcoming'}
