import {db,json,HttpError,notification} from './server';
import {OWNER_EMAIL,type Member,type StoredRecord,canRead} from './permissions';
import {idList} from './field-rules';
const text=(s:string)=>String(s||'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const phone=(s:string)=>String(s||'').replace(/\D/g,'').slice(-10);
export function matchesCustomer(a:Record<string,string>,b:Record<string,string>){const phones=(d:Record<string,string>)=>[d['Mobile 1'],d['Mobile 2'],d.Phone].map(phone).filter(p=>p.length===10);const reg=text(a['Registration no']);return text(a.Name)!==''&&text(a.Name)===text(b.Name)||!!reg&&reg===text(b['Registration no'])||phones(a).some(p=>phones(b).includes(p));}
export function accessRoute(m:Member,d:Record<string,string>){try{const grants=JSON.parse(d['MR route access']||'{}');const id=grants[m.email];return typeof id==='string'&&idList(m.route_ids).includes(id)?id:''}catch{return ''}}
export async function duplicateRequest(m:Member,data:Record<string,string>,id?:string){const all=(await db().prepare("SELECT * FROM records WHERE kind='Customers' AND id<>?").bind(id||'').all<StoredRecord>()).results.filter(r=>matchesCustomer(data,JSON.parse(r.data)));if(!all.length)return null;if(m.role==='admin')throw new HttpError(409,`Possible duplicate: ${all.map(r=>JSON.parse(r.data).Name).join(', ')}. Review existing customers before saving.`);if(all.some(r=>canRead(m,r)))throw new HttpError(409,'A matching customer is already available in your directory. Use that profile.');
 const prior=await db().prepare("SELECT id FROM workflow_requests WHERE kind='customer_access' AND mr_email=? AND record_id=? AND status='Pending'").bind(m.email,all[0].id).first<{id:string}>();const requestId=prior?.id||crypto.randomUUID();if(!prior)await db().batch([db().prepare("INSERT INTO workflow_requests(id,kind,mr_email,record_id,body,status,created) VALUES (?,'customer_access',?,?,?,'Pending',?)").bind(requestId,m.email,all[0].id,JSON.stringify({routeId:data['Route ID'],submitted:data,candidates:all.map(r=>r.id)}),new Date().toISOString()),notification(OWNER_EMAIL,'Customer access requested',`${m.name} found a possible duplicate for ${data.Name}. Review route access.`,'Approvals',requestId)]);return json({ok:true,accessRequested:true,message:'Possible duplicate found. Your request to access the existing customer has been sent to Admin.'});}
