import {attendanceMonth} from './attendance';
import {customerVisible,idList} from './field-rules';
import type {Member} from './permissions';
export type Row=Record<string,any>;
export type ReportTable={title:string;columns:string[];rows:(string|number)[][];note?:string;webOnly?:boolean};
export const rupees=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(paise/100);
export const owned=(r:Row,m:Member)=>r.assigned_to?r.assigned_to===m.email:!!m.user_id&&r.owner===m.user_id;
export function totals(m:Member,month:string,records:Row[],invoices:Row[]){
 const saved=records.find(r=>r.id===`monthly-target:${m.email}:${month}`),target=Number(saved?.data['MR monthly target']??m.target)*100;
 const legacy=records.filter(r=>r.kind==='Secondary sales'&&!r.data['Invoice ID']&&owned(r,m)&&(r.data.Date||r.created).startsWith(month));
 const achieved=invoices.filter(i=>i.kind==='secondary'&&(i.status===undefined||i.status==='Delivered')&&i.mr_email===m.email&&i.date.startsWith(month)).reduce((n,i)=>n+i.subtotal,0)+legacy.reduce((n,r)=>n+Math.round(Number(r.data.Quantity||0)*Number(r.data.Rate||0)*100),0);
 return {email:m.email,name:m.name,target,achieved,pending:Math.max(0,target-achieved),exceeded:Math.max(0,achieved-target),percentage:target?achieved/target*100:0,targetSaved:!!saved};
}
export function buildReport(m:Member,month:string,records:Row[],invoices:Row[],movements:Row[],benefits:Row[],commitments:Row[],admin:boolean){
 records=records.map(r=>{if(r.kind!=='Customers')return r;let routeId='';try{routeId=JSON.parse(r.data['MR route access']||'{}')[m.email]}catch{}if(!idList(m.route_ids).includes(routeId))return r;const route=records.find(x=>x.id===routeId);return route?{...r,data:{...r.data,Route:route.data.Name,'Route ID':routeId,District:route.data.District}}:r});
 const next=new Date(`${month}-01T00:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);const end=next.toISOString().slice(0,10),start=month+'-01';
 const name=(id:string)=>records.find(r=>r.id===id)?.data.Name||id||'—',byId=new Map(invoices.map(i=>[i.id,i]));
 const current=idList(m.stockist_ids),historical=invoices.filter(i=>i.kind==='secondary'&&(i.status===undefined||i.status==='Delivered')&&i.mr_email===m.email&&i.date<end).map(i=>i.stockist_id),stockists=[...new Set([...current,...historical])];
 const mine=records.filter(r=>owned(r,m)),period=mine.filter(r=>(r.data.Date||r.created).startsWith(month));
 const visits=period.filter(r=>r.kind==='Visits'),secondary=invoices.filter(i=>i.kind==='secondary'&&(i.status===undefined||i.status==='Delivered')&&i.mr_email===m.email&&i.date.startsWith(month)),primary=invoices.filter(i=>i.kind==='primary'&&stockists.includes(i.stockist_id)&&i.date.startsWith(month));
 const pendingOrders=invoices.filter(i=>i.kind==='secondary'&&i.mr_email===m.email&&i.date.startsWith(month)&&i.status&&i.status!=='Delivered');
 const tables:ReportTable[]=[],add=(title:string,columns:string[],rows:(string|number)[][],note?:string)=>tables.push({title,columns,rows,note});
 add('Placed and cancelled orders — not recognised as sales',['Order number','Date','Customer','Agency','Status','Net order value'],pendingOrders.map(i=>[i.number,i.date,name(i.customer_id),name(i.stockist_id),i.status,rupees(i.subtotal)]),'Placed orders reserve stock but do not reduce physical agency stock. Delivered orders are recognised against the order date. Cancelled orders are excluded from achievement.');
 const salesRows=(list:Row[],primary=false)=>list.flatMap(i=>i.items.map((l:Row)=>[i.date,i.number,name(i.stockist_id),...(primary?[]:[name(i.customer_id)]),l.name,l.qty,l.free,l.scheme==='none'?'Nil':l.scheme,...(primary&&!admin?[]:[rupees(l.rate),`${l.gst}%`,rupees(l.subtotal),...(primary?[]:[rupees(l.total)])]),...(primary&&!admin?[rupees(i.subtotal)]:[]),i.notes||'—']));
 add('Secondary sales — order and product detail',['Date','Order number','Agency','Customer','Product','Paid qty','Free qty','Scheme','Rate','GST','Net value','Incl. GST','Notes'],salesRows(secondary));
 add('Primary sales — linked agencies',['Date','Invoice','Agency','Product','Paid qty','Free qty','Scheme',...(admin?['PTS','GST rate','Net value excl. GST']:['Invoice net excl. GST']), 'Notes'],salesRows(primary,true),'Shared agency billing is shown in full, not credited to this MR’s target. Agency scope uses current assignments plus agencies in this MR’s recorded orders. Net invoice totals repeat on each product row in MR view; do not sum them.');
 const products=new Map<string,Row>();for(const i of secondary)for(const l of i.items){const c=products.get(l.productId)||{name:l.name,qty:0,free:0,net:0,total:0};c.qty+=l.qty;c.free+=l.free;c.net+=l.subtotal;c.total+=l.total;products.set(l.productId,c)}
 add('Product-wise secondary sales',['Product','Paid qty','Free qty','Total units','Net sales','Incl. GST'],[...products.values()].sort((a,b)=>b.net-a.net).map(c=>[c.name,c.qty,c.free,c.qty+c.free,rupees(c.net),rupees(c.total)]));
 const customerMap=new Map<string,Row>();
 for(const i of secondary){const c=customerMap.get(i.customer_id)||{id:i.customer_id,orders:0,net:0,total:0,qty:0,free:0};c.orders++;c.net+=i.subtotal;c.total+=i.total;for(const l of i.items){c.qty+=l.qty;c.free+=l.free;}customerMap.set(i.customer_id,c)}
 add('Highest order-value customers',['Rank','Customer','Route','Orders','Paid qty','Free qty','Net sales','Incl. GST','Largest order incl. GST'],[...customerMap.values()].sort((a,b)=>b.net-a.net).map((c,i)=>[i+1,name(c.id),records.find(r=>r.id===c.id)?.data.Route||'—',c.orders,c.qty,c.free,rupees(c.net),rupees(c.total),rupees(Math.max(...secondary.filter(s=>s.customer_id===c.id).map(s=>s.total)))]));
 const issued=new Map<string,Row>();for(const i of secondary)for(const l of i.items){const k=i.customer_id+'|'+i.stockist_id+'|'+l.productId,c=issued.get(k)||{customer:i.customer_id,agency:i.stockist_id,product:l.name,qty:0,free:0,total:0};c.qty+=l.qty;c.free+=l.free;c.total+=l.total;issued.set(k,c)}
 add('Customer-wise product quantities issued',['Customer','Agency','Product','Paid qty','Free qty','Total units','Bill value'],[...issued.values()].map(c=>[name(c.customer),name(c.agency),c.product,c.qty,c.free,c.qty+c.free,rupees(c.total)]),'These are order-issued quantities, not verified customer remaining stock or proof of delivery.');
 const visitCustomer=(v:Row)=>v.data['Customer ID']||records.find(r=>r.kind==='Customers'&&r.data.Name===v.data.Customer)?.id||v.data.Customer||'Unknown',groups=new Map<string,Row[]>();for(const v of visits){const k=visitCustomer(v);groups.set(k,[...(groups.get(k)||[]),v])}
 add('Customer coverage and repeat visits',['Customer','Category','Route','Visits','Repeat visits','Visit dates'],[...groups.entries()].sort((a,b)=>b[1].length-a[1].length).map(([id,vs])=>{const c=records.find(r=>r.id===id||r.kind==='Customers'&&r.data.Name===id);return[c?.data.Name||id,c?.data['Customer category']||c?.data.Type||'Doctor',c?.data.Route||'—',vs.length,Math.max(0,vs.length-1),vs.map(v=>v.data.Date).join(', ')]}));
 add('All doctor and customer visits',['Date','Customer','Route','Purpose','Response','Status','Follow-up','GPS','Notes'],visits.map(v=>[v.data.Date,v.data.Customer||name(v.data['Customer ID']),v.data.Route||records.find(r=>r.id===v.data['Customer ID'])?.data.Route||'—',v.data.Purpose||'—',v.data.Response||'—',v.data.Status||'Open',v.data['Follow-up date']||'—',v.data.Location||'Not recorded',v.data.Notes||'—']));
 const stock=new Map<string,Row>(),running:Row[]=[];
 const scoped=movements.filter(s=>stockists.includes(s.stockist_id)&&byId.get(s.invoice_id)?.date<end).sort((a,b)=>{const x=byId.get(a.invoice_id)!,y=byId.get(b.invoice_id)!;return x.date.localeCompare(y.date)||a.created.localeCompare(b.created)||a.id.localeCompare(b.id)});
 for(const s of scoped){const i=byId.get(s.invoice_id)!,key=s.stockist_id+'|'+s.product_id,b=stock.get(key)||{agency:s.stockist_id,product:s.product_id,opening:0,received:0,issued:0,mine:0,balance:0};b.balance+=s.quantity;if(i.date<start)b.opening+=s.quantity;else{if(i.kind==='primary')b.received+=s.quantity;else{b.issued-=s.quantity;if(i.mr_email===m.email)b.mine-=s.quantity}running.push({s,i,balance:b.balance})}stock.set(key,b)}
 add('Agency stock reconciliation at month end',['Agency','Product','Opening','Primary received','Secondary issued — all MRs','Issued by this MR','Closing'],[...stock.values()].map(s=>[name(s.agency),name(s.product),s.opening,s.received,s.issued,s.mine,s.balance]),'Opening + primary receipts − all MRs’ secondary issues = closing. Includes paid and free units. Uses invoice dates; later edits or backdated entries can restate a previous month. Legacy sales are not included in this stock ledger.');
 add('Agency stock after each invoice / order adjustment',['Date','Invoice / order number','Agency','Product','Movement','Units','Balance after entry','MR / source'],running.map(({s,i,balance})=>[i.date,i.number,name(s.stockist_id),name(s.product_id),i.kind==='primary'?'Primary receipt':s.quantity>0?'Order edit — stock restored':'Secondary issue / edit',s.quantity,balance,i.kind==='primary'?'Company':i.mr_email===m.email?m.name:admin?i.mr_email:'Other MR']));
 const localDate=(s:string)=>new Date(s).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'}),bm=benefits.filter(b=>b.mr_email===m.email&&localDate(b.created)<end),benefitPeriod=bm.filter(b=>localDate(b.created)>=start),bb=new Map<string,Row>();
 for(const b of bm){const k=b.kind+'|'+b.item_id,c=bb.get(k)||{kind:b.kind,id:b.item_id,opening:0,allotted:0,issued:0,returned:0,balance:0,value:0,cost:0};c.balance+=b.quantity;c.value+=b.cost;if(localDate(b.created)<start)c.opening+=b.quantity;else{if(b.movement==='allocate')c.allotted+=b.quantity;else if(b.movement==='return')c.returned-=b.quantity;else{c.issued-=b.quantity;c.cost-=b.cost}}bb.set(k,c)}
 add('Samples and gifts — allocation, usage and closing balance',['Type','Item','Opening qty','Allotted','Issued','Returned','Closing qty','Usage cost','Closing cost'],[...bb.values()].map(b=>[b.kind,name(b.id),b.opening,b.allotted,b.issued,b.returned,b.balance,rupees(b.cost),rupees(b.value)]));
 add('Samples and gifts — customer-wise detail',['Date','Type','Movement','Item','Customer','Qty','Cost','Visit','GPS'],benefitPeriod.map(b=>[localDate(b.created),b.kind,b.movement,name(b.item_id),name(b.customer_id),Math.abs(b.quantity),rupees(Math.abs(b.cost)),b.visit_id||'—',b.gps||'—']));
 add('Order sample commitments — current fulfilment',['Order number','Customer','Product','Committed','Fulfilled now','Pending now','Notes'],commitments.filter(c=>c.mr_email===m.email&&byId.get(c.invoice_id)?.date<end).map(c=>[byId.get(c.invoice_id)?.number||c.invoice_id,name(c.customer_id),name(c.product_id),c.quantity,c.fulfilled,Math.max(0,c.quantity-c.fulfilled),c.notes||'—']),'Fulfilment is the current status at report generation, including fulfilments after the selected month.');
 const attendance=attendanceMonth(m,month,records);add('Attendance - daily completion and GPS',['Date','Day','Status','Check-in','In GPS','Checkout','Out GPS','Duration'],attendance.days.map(d=>[d.date,d.weekday,d.label,d.checkin,d.inGPS?'Recorded':d.status==='future'?'—':'Missing',d.checkout,d.outGPS?'Recorded':d.status==='future'?'—':'Missing',d.duration]),'Green requires both check-in and checkout with valid recorded GPS. Missing records do not establish absence; leave and weekly-off rules are not configured. Times are IST.');
 for(const kind of ['Tour plan','Expenses']){const cols=kind==='Attendance'?['Date','Action','Time','Location','Notes']:kind==='Expenses'?['Date','Category','Amount','Status','Notes']:['Date','Route','Purpose','Status','Notes'];add(kind,cols,period.filter(r=>r.kind===kind).map(r=>cols.map(k=>k==='Amount'?rupees(Number(r.data[k]||0)*100):r.data[k]||'—')))}
 add('Field activity — complete recorded details',['Activity','Date','Details'],period.filter(r=>['Visits','Attendance','Tour plan','Expenses'].includes(r.kind)).map(r=>[r.kind,r.data.Date||r.created,Object.entries(r.data).map(([k,v])=>`${k}: ${v}`).join(' · ')]));
 tables[tables.length-1].webOnly=true;
 const legacy=period.filter(r=>['Orders','Primary sales','Secondary sales','Samples'].includes(r.kind)&&!r.data['Invoice ID']&&!r.data['Ledger ID']);
 add('Legacy records — retained history',['Type','Date','Details'],legacy.map(r=>[r.kind,r.data.Date||r.created,Object.entries(r.data).map(([k,v])=>`${k}: ${v}`).join(' · ')]),'Legacy secondary sales contribute to achievement, but do not change agency stock. Legacy orders are not counted again as secondary orders.');
 const customers=records.filter(r=>r.kind==='Customers'&&(customerVisible(m,{...r,data:JSON.stringify(r.data)} as any)||admin&&(customerMap.has(r.id)||groups.has(r.id)||groups.has(r.data.Name))));
 add('Customer directory and registration details',['Name','Category','Route','Details'],customers.map(c=>[c.data.Name||'—',c.data['Customer category']||c.data.Type||'Doctor',c.data.Route||'—',Object.entries(c.data).filter(([k])=>!['Name','GPS data','MR route access','Blocked MRs'].includes(k)).map(([k,v])=>`${k}: ${v}`).join(' · ')]));
 return {month,generated:new Date().toISOString(),member:{name:m.name,employeeCode:m.employee_code,phone:m.phone,headquarters:m.headquarters,territory:m.territory,routes:idList(m.route_ids).map(name).join(', ')||m.route,districts:idList(m.district_ids).map(name).join(', ')||m.district},summary:totals(m,month,records,invoices),metrics:{visits:visits.length,closedVisits:visits.filter(v=>v.data.Status==='Closed').length,customersVisited:groups.size,repeatVisits:[...groups.values()].reduce((n,v)=>n+Math.max(0,v.length-1),0),orders:secondary.length,primary:primary.reduce((n,i)=>n+i.subtotal,0),workingDays:new Set(period.filter(r=>r.kind==='Attendance'&&r.data.Action==='Check in').map(r=>r.data.Date)).size,benefitCost:benefitPeriod.filter(b=>b.movement==='issue').reduce((n,b)=>n-b.cost,0)},tables};
}
