import {db,HttpError} from './server';
import {canRead,type StoredRecord,type Member} from './permissions';
import {validGPS,type GPSPoint,idList} from './field-rules';
export const indiaDay=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export async function record(id:string,kind:string){const r=await db().prepare('SELECT * FROM records WHERE id=? AND kind=?').bind(id,kind).first<StoredRecord>();if(!r)throw new HttpError(400,`${kind} record is unavailable.`);return {...r,details:JSON.parse(r.data) as Record<string,string>};}
export async function customer(m:Member,id:string){const r=await record(id,'Customers');if(!canRead(m,r))throw new HttpError(403,'This customer is not assigned to you.');return r;}
export function stockistAllowed(m:Member,id:string){return m.role==='admin'||idList(m.stockist_ids).includes(id);}
export function requireGPS(g:unknown):GPSPoint{if(!validGPS(g))throw new HttpError(400,'Capture fresh GPS before saving. Location is mandatory.');return g;}
export async function activeDay(m:Member){const r=await db().prepare("SELECT data FROM records WHERE kind='Attendance' AND json_extract(data,'$.Date')=? AND (assigned_to=? OR (assigned_to='' AND owner=?)) ORDER BY created DESC,rowid DESC LIMIT 1").bind(indiaDay(),m.email,m.user_id).first<{data:string}>();if(!r||JSON.parse(r.data).Action!=='Check in')throw new HttpError(409,'Start my day before recording or closing a visit.');}
export function ledgerFailure(e:unknown){const message=String(e);if(message.includes('PERIOD_CLOSED'))throw new HttpError(409,'This period is closed. Admin must reopen this and any later closed months first.');if(message.includes('STALE_REVIEW'))throw new HttpError(409,'Data changed during review. Refresh and review again.');if(message.includes('ATTENDANCE_REQUIRED'))throw new HttpError(409,'Check in before closing this visit.');if(message.includes('INSUFFICIENT_STOCK'))throw new HttpError(409,'Stock changed or is insufficient. Refresh stock and reduce the quantity, including free units.');if(message.includes('GIFT_ALREADY_SUPPLIED'))throw new HttpError(409,'Already supplied: this gift was previously given to this customer.');if(message.includes('INSUFFICIENT_ALLOTMENT'))throw new HttpError(409,'The MR does not have enough allotted sample or gift stock.');if(message.includes('COMMITMENT_EXCEEDED'))throw new HttpError(409,'The sample commitment has already been fulfilled.');if(message.includes('UNIQUE constraint'))throw new HttpError(409,'This entry has already been saved. Refresh to see it.');throw e;}
export function guard(kind:'stock'|'benefit'|'gift'|'commitment'|'attendance'|'period'|'version',condition:string,args:(string|number|null)[]=[]){return db().prepare(`INSERT OR REPLACE INTO ledger_guards(id,${kind}) VALUES ('transaction',CASE WHEN (${condition}) THEN 1 ELSE 0 END)`).bind(...args);}
export function benefitPosting(id:string,kind:'sample'|'gift'){
 const statements=[db().prepare("INSERT INTO benefit_balances(id,kind,mr_email,item_id,quantity,value) SELECT kind||'|'||mr_email||'|'||item_id,kind,mr_email,item_id,quantity,cost FROM benefit_movements WHERE id=? ON CONFLICT(id) DO UPDATE SET quantity=quantity+excluded.quantity,value=value+excluded.value").bind(id),guard('benefit',"NOT EXISTS(SELECT 1 FROM benefit_balances b JOIN benefit_movements m ON b.id=m.kind||'|'||m.mr_email||'|'||m.item_id WHERE m.id=? AND (b.quantity<0 OR b.value<0))",[id])];
 if(kind==='sample')statements.push(db().prepare("INSERT INTO records(id,owner,kind,data,created,assigned_to) SELECT 'benefit:'||m.id,COALESCE((SELECT user_id FROM members WHERE email=m.mr_email),''),'Samples',json_object('Date',date(m.created,'+5 hours','+30 minutes'),'Product',(SELECT json_extract(data,'$.Name') FROM records WHERE id=m.item_id),'Customer',COALESCE((SELECT json_extract(data,'$.Name') FROM records WHERE id=m.customer_id),''),'Movement',CASE WHEN m.movement='allocate' THEN 'Issued to rep' WHEN m.movement='return' THEN 'Returned' ELSE 'Given to customer' END,'Quantity',CAST(ABS(m.quantity) AS TEXT),'Unit cost',CAST(ABS(m.cost)*1.0/ABS(m.quantity)/100 AS TEXT),'Representative',(SELECT name FROM members WHERE email=m.mr_email),'Ledger ID',m.id),m.created,m.mr_email FROM benefit_movements m WHERE m.id=?").bind(id));
 return statements;
}
export async function issueStatements(m:Member,kind:'gift'|'sample',itemId:string,qty:number,customerId:string,visitId:string,gps:GPSPoint|null,entryId=crypto.randomUUID(),movement:'issue'|'return'='issue'){
 const r=await record(itemId,kind==='gift'?'Gifts':'Products');
 if(!Number.isInteger(qty)||qty<1||qty>100000)throw new HttpError(400,'Use a positive whole quantity.');
 const key=`${kind}|${m.email}|${itemId}`,statements=[];
 if(kind==='gift'&&movement==='issue')statements.push(guard('gift',"NOT(COALESCE((SELECT json_extract(data,'$.\"One per customer\"') FROM records WHERE id=?),'Yes')='Yes' AND EXISTS(SELECT 1 FROM benefit_movements WHERE kind='gift' AND movement='issue' AND item_id=? AND customer_id=?))",[itemId,itemId,customerId]));
 statements.push(db().prepare("INSERT INTO benefit_movements(id,kind,movement,mr_email,item_id,customer_id,visit_id,quantity,cost,gps,created) VALUES (?,?,?,?,?,?,?,?,-COALESCE((SELECT ROUND(value*?*1.0/quantity) FROM benefit_balances WHERE id=? AND quantity>=?),0),?,?)").bind(entryId,kind,movement,m.email,r.id,customerId,visitId,-qty,qty,key,qty,gps?JSON.stringify(gps):'',new Date().toISOString()));
 statements.push(...benefitPosting(entryId,kind));return statements;
}
