import {db,HttpError} from './server';
import {guard} from './operations';
import {buildReport,type Row} from './monthly-report';
import {routeInsights,shiftMonth} from './route-insights';
import type {Member} from './permissions';
export function periodGuard(date:string){return guard('period','NOT EXISTS(SELECT 1 FROM period_locks WHERE closed=1 AND month>=?)',[date.slice(0,7)])}
export async function assertOpen(date:string){if(await db().prepare('SELECT month FROM period_locks WHERE closed=1 AND month>=? LIMIT 1').bind(date.slice(0,7)).first())throw new HttpError(409,'This period or a later month is closed. Ask Admin to reopen it before changing history.')}
export const stateSQL=`SELECT json_array((SELECT json_group_array(json_array(id,revision,status,accepted)) FROM (SELECT * FROM invoices ORDER BY id)),(SELECT json_group_array(json_array(id,data,assigned_to)) FROM (SELECT * FROM records ORDER BY id)),(SELECT json_group_array(json_array(id,quantity,cost)) FROM (SELECT * FROM benefit_movements ORDER BY id)),(SELECT json_group_array(json_array(id,fulfilled)) FROM (SELECT * FROM commitments ORDER BY id)),(SELECT json_group_array(json_array(id,quantity)) FROM (SELECT * FROM stock_movements ORDER BY id)),(SELECT json_group_array(json_array(email,target,route_ids,stockist_ids)) FROM (SELECT * FROM members ORDER BY email))) AS stamp`;
export async function reportingData(){const [r,i,s,b,c]=await Promise.all([db().prepare('SELECT * FROM records').all<Row>(),db().prepare('SELECT * FROM invoices').all<Row>(),db().prepare('SELECT * FROM stock_movements').all<Row>(),db().prepare('SELECT * FROM benefit_movements').all<Row>(),db().prepare('SELECT * FROM commitments').all<Row>()]);return {records:r.results.map(r=>({...r,data:JSON.parse(r.data)})),invoices:i.results.map((i):Row=>({...i,items:JSON.parse(i.items)})),stock:s.results,benefits:b.results,commitments:c.results}}
export function makeReport(m:Member,month:string,data:Awaited<ReturnType<typeof reportingData>>,admin=true){const r=buildReport(m,month,data.records,data.invoices,data.stock,data.benefits,data.commitments,admin);r.tables.push(...routeInsights(m,month,shiftMonth(month,-1),3,data.records,data.invoices).tables);return r}
