import {customerVisible,idList} from './field-rules';
import type {Member} from './permissions';
import type {ReportTable,Row} from './monthly-report';
const value=(p:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(p/100);
export function shiftMonth(month:string,n:number){const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,7)}
export function routeInsights(m:Member,month:string,compare:string,inactive:number,records:Row[],invoices:Row[]){
 records=records.map(r=>{if(r.kind!=='Customers')return r;let rid='';try{rid=JSON.parse(r.data['MR route access']||'{}')[m.email]}catch{}if(!idList(m.route_ids).includes(rid))return r;const route=records.find(x=>x.id===rid);return route?{...r,data:{...r.data,Route:route.data.Name,'Route ID':rid}}:r});
 const end=shiftMonth(month,1)+'-01',cutoff=shiftMonth(month,-inactive)+'-01',belongs=(r:Row)=>r.assigned_to?r.assigned_to===m.email:!!m.user_id&&r.owner===m.user_id;
 const visits=records.filter(r=>r.kind==='Visits'&&belongs(r)),customerID=(r:Row)=>r.data['Customer ID']||records.find(c=>c.kind==='Customers'&&c.data.Name===r.data.Customer)?.id||r.data.Customer;
 const allOrders=invoices.filter(i=>i.kind==='secondary'&&i.status!=='Cancelled'&&i.mr_email===m.email).map(i=>({id:i.id,customer:i.customer_id,date:i.date,net:i.subtotal,number:i.number}));
 const legacy=records.filter(r=>['Secondary sales','Orders'].includes(r.kind)&&!r.data['Invoice ID']&&belongs(r)&&r.data.Status!=='Cancelled');
 const orderHistory=[...allOrders,...legacy.map(r=>({id:r.id,customer:customerID(r),date:r.data.Date||r.created.slice(0,10),net:r.kind==='Secondary sales'?Math.round(Number(r.data.Quantity||0)*Number(r.data.Rate||0)*100):0,number:r.data['Order number']||r.data['Invoice number']||'Legacy entry'}))];
 const salesHistory=[...allOrders.filter(o=>{const i=invoices.find(i=>i.id===o.id);return !i?.status||i.status==='Delivered'}),...legacy.filter(r=>r.kind==='Secondary sales').map(r=>({id:r.id,customer:customerID(r),date:r.data.Date||r.created.slice(0,10),net:Math.round(Number(r.data.Quantity||0)*Number(r.data.Rate||0)*100),number:'Legacy sale'}))];
 const activityIDs=new Set([...visits.map(customerID),...orderHistory.map(o=>o.customer)]);
 const customers=records.filter(r=>r.kind==='Customers'&&(customerVisible(m,{...r,data:JSON.stringify(r.data)} as any)||activityIDs.has(r.id))&&(r.created.slice(0,10)<end));
 const routeName=(id:string)=>records.find(r=>r.id===id)?.data.Name||'',routes=[...new Set([...idList(m.route_ids).map(routeName),...customers.map(c=>c.data.Route||'Unassigned')])].filter(Boolean).sort();
 const byCustomer=(id:string)=>customers.find(c=>c.id===id),routeOf=(id:string)=>byCustomer(id)?.data.Route||'Unassigned';
 if(!routes.includes('Unassigned')&&(visits.some(v=>routeOf(customerID(v))==='Unassigned')||salesHistory.some(o=>routeOf(o.customer)==='Unassigned')))routes.push('Unassigned');
 const table:ReportTable={title:`Route performance — ${month} vs ${compare}`,columns:['Route','Customers','Visits '+month,'Visits '+compare,'Orders '+month,'Orders '+compare,'Net sales '+month,'Net sales '+compare,'Sales change','Change %','Never visited','Visited / no orders'],rows:[]};
 const periodStats=(route:string,period:string)=>{const v=visits.filter(v=>(v.data.Date||v.created).startsWith(period)&&routeOf(customerID(v))===route),o=salesHistory.filter(o=>o.date.startsWith(period)&&routeOf(o.customer)===route);return {visits:v.length,orders:orderHistory.filter(o=>o.date.startsWith(period)&&routeOf(o.customer)===route).length,sales:o.reduce((n,o)=>n+o.net,0)}};
 const never=customers.filter(c=>!visits.some(v=>customerID(v)===c.id&&(v.data.Date||v.created).slice(0,10)<end));
 const visitedNoOrders=customers.filter(c=>visits.some(v=>customerID(v)===c.id&&(v.data.Date||v.created).startsWith(month))&&!orderHistory.some(o=>o.customer===c.id&&o.date.startsWith(month)));
 const priorNoOrders=customers.map(c=>({c,orders:orderHistory.filter(o=>o.customer===c.id&&o.date<end).sort((a,b)=>b.date.localeCompare(a.date))})).filter(({orders})=>orders.length&&orders[0].date<cutoff);
 for(const route of routes){const a=periodStats(route,month),b=periodStats(route,compare);table.rows.push([route,customers.filter(c=>(c.data.Route||'Unassigned')===route).length,a.visits,b.visits,a.orders,b.orders,value(a.sales),value(b.sales),value(a.sales-b.sales),b.sales?((a.sales-b.sales)/b.sales*100).toFixed(1)+'%':a.sales?'New sales (zero base)':'—',never.filter(c=>(c.data.Route||'Unassigned')===route).length,visitedNoOrders.filter(c=>(c.data.Route||'Unassigned')===route).length])}
 table.note='Sales exclude GST. Route grouping uses current customer routes. Order counts include placed and delivered orders; cancelled orders are excluded. Sales include delivered orders only. Legacy entries are included; old legacy entries may be product-level records. Never-visited history ends at the selected month end.';
 const contact=(c:Row)=>[c.data.Name||'—',c.data.Route||'Unassigned',c.data['Customer category']||c.data.Type||'Doctor',c.data['Mobile 1']||c.data.Phone||'—'];
 const tables:ReportTable[]=[table,{title:'Customers never visited',columns:['Customer','Route','Category','Phone','Registered'],rows:never.map(c=>[...contact(c),c.created.slice(0,10)]),note:'No recorded visit by this MR at any time up to the selected month end. This does not imply the customer has never been visited by another MR.'},{title:'Visited customers without orders in selected month',columns:['Customer','Route','Category','Phone','Visits','Last visit','Last order before month end'],rows:visitedNoOrders.map(c=>{const vs=visits.filter(v=>customerID(v)===c.id&&(v.data.Date||v.created).startsWith(month));return [...contact(c),vs.length,vs.map(v=>v.data.Date||v.created.slice(0,10)).sort().at(-1)||'—',orderHistory.filter(o=>o.customer===c.id&&o.date<end).map(o=>o.date).sort().at(-1)||'Never ordered']})},{title:`Previously ordering customers inactive for ${inactive} completed months`,columns:['Customer','Route','Category','Phone','Last order date','Last order number','Last order net','Days since last order at month end'],rows:priorNoOrders.map(({c,orders})=>[...contact(c),orders[0].date,orders[0].number,value(orders[0].net),Math.floor((Date.parse(end)-Date.parse(orders[0].date))/86400000)-1]),note:`Previously ordered, but no recorded order from ${cutoff} through the end of ${month}. Includes the previous ${inactive} complete calendar months and the selected month.`},{title:'Customers with no order history',columns:['Customer','Route','Category','Phone','Registered'],rows:customers.filter(c=>!orderHistory.some(o=>o.customer===c.id&&o.date<end)).map(c=>[...contact(c),c.created.slice(0,10)]),note:'Kept separate from previously ordering customers who stopped ordering.'}];
 return {month,compare,inactive,mr:m.name,tables};
}
