export type FieldRecord={id:string;kind:string;data:Record<string,string>;created:string;assigned_to:string;owner:string};
export type Notice={id:string;title:string;body:string;module:string;record_id:string|null;created:string;read_at:string|null};
export const fields:Record<string,string[]>={Customers:['Name','Type','Phone','District','Headquarters','Route','Territory','Address','Species focus','Notes'],Stockists:['Name','Phone','WhatsApp number','District','Headquarters','Route','Territory','Address'],Products:['Name','Pack','Species focus','MRP','PTR','PTS','GST %','Offer rate','Special rate','Price mode','Scheme enabled','Scheme paid quantity','Scheme free quantity','Visual aid URL'],Visits:['Customer','Date','Purpose','Products discussed','Response','Follow-up date','Notes','Location'],'Tour plan':['Customer','Date','Visit sequence','Purpose','Status'],Orders:['Customer','Stockist','Date','Product','Quantity','Free quantity','Rate','GST %','Status','Notes'],'Secondary sales':['Customer','Stockist','Date','Product','Quantity','Free quantity','Rate','Order number','Notes'],'Primary sales':['Stockist','Date','Product','Quantity','Free quantity','Rate','Invoice number'],Samples:['Date','Product','Movement','Quantity','Unit cost','Customer','Notes'],Expenses:['Date','Category','Amount','Status','Notes'],Attendance:['Date','Action','Time','Location'],Settings:['Monthly target','Territory'],Districts:['Name','State','Notes'],Headquarters:['Name','District','Address','Notes'],Routes:['Name','District','Headquarters','Coverage / stops','Working days','Notes'],'MR types':['Name','Description']};
export const options:Record<string,string[]>={Type:['Veterinary Doctor','Clinic / Hospital','Pharmacy','Agency','Dairy Farm','Poultry Farm','Sheep / Goat Farm','Pet Clinic','Institution','Other'],Purpose:['Routine','Product detailing','Order','New launch','Follow-up','Complaint'],Response:['Interested','Very interested','Trial requested','Already using','Not interested','Follow-up required'],Category:['Fuel','Travel','Food','Stay','Toll / Parking','Courier','Marketing','Other'],Movement:['Issued to rep','Given to customer','Returned'],'Price mode':['PTR','PTS','Offer rate','Special rate'],'Scheme enabled':['No','Yes'],Action:['Check in','Check out','Leave']};
export const numeric=['Quantity','Free quantity','Rate','MRP','PTR','PTS','GST %','Amount','Unit cost','Monthly target','Visit sequence','Scheme paid quantity','Scheme free quantity','Offer rate','Special rate'];
export const descriptions:Record<string,string>={Dashboard:'A clear view of your people, visits and market movement.',Customers:'Doctors, medicals, clinics, farmers and Livestock Inspectors.',Stockists:'Your supplying partners, organised by territory.',Products:'Your product catalogue and trade prices.','Tour plan':'Plan your route and make every visit count.',Visits:'Capture conversations, product interest and follow-ups.',Orders:'Follow customer demand from request to supply.','Secondary sales':'Sales from your stockists to the market.','Primary sales':'Company billing to your stockist network.',Samples:'Keep track of samples issued and given to customers.',Expenses:'Submit field expenses and track approvals.',Attendance:'Start your day and record your field presence.','Route performance':'Compare routes across months and identify customers needing follow-up.','Follow-ups':'Schedule customer next actions and track completion.','Approvals':'Review customer access and order change requests.','Month closing':'Approve monthly reports and control changes to closed periods.',Reports:'Your activity and sales, ready to review and export.',Settings:'Set the management sales target.',Districts:'Maintain the districts covered by your field team.',Headquarters:'Organise headquarters within each district.',Routes:'Create field routes and assign them to representatives.','MR types':'Define MR categories for your business.','MR activity':'Review visits, orders, expenses and attendance by representative.',Locations:'Last recorded GPS from MR visits and attendance.',Performance:'Compare monthly sales, calls and target achievement.',Team:'Manage MR access, territories and individual targets.',Notifications:'Your assignments and updates, all in one inbox.'};
export const singular:Record<string,string>={Customers:'customer',Stockists:'stockist',Products:'product','Tour plan':'planned visit',Visits:'visit',Orders:'order','Secondary sales':'secondary sale','Primary sales':'primary sale',Samples:'sample entry',Expenses:'expense',Attendance:'attendance',Settings:'settings',Districts:'district',Headquarters:'headquarters',Routes:'route','MR types':'MR type'};
export const columns:Record<string,string[]>={Customers:['Name','Type','Route','Phone','Email'],Stockists:['Name','District','Phone'],Products:['Name','Pack','MRP','PTR','PTS','Offer rate','Special rate','Price mode','Scheme'],Visits:['Customer','Date','Purpose','Response'],'Tour plan':['Customer','Date','Purpose','Status'],Orders:['Customer','Stockist','Product','Quantity','Status'],'Secondary sales':['Customer','Stockist','Product','Quantity','Date'],'Primary sales':['Stockist','Product','Quantity','Date'],Samples:['Product','Customer','Movement','Quantity'],Expenses:['Category','Date','Amount','Status'],Attendance:['Date','Representative','Action','Time'],Settings:['Monthly target','Territory'],Districts:['Name','State','Notes'],Headquarters:['Name','District','Address','Notes'],Routes:['Name','District','Headquarters','Coverage / stops','Working days','Notes'],'MR types':['Name','Description']};
export const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export const recordValue=(r:FieldRecord)=>Number(r.data.Quantity||0)*Number(r.data.Rate||0);
export function initials(name:string){return name.split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase()||'VM'}
export function dateLabel(s:string){return new Date(s).toLocaleDateString('en-IN',{day:'numeric',month:'short',timeZone:'Asia/Kolkata'})}

Object.assign(columns,{Districts:['Name','State'],Headquarters:['Name','District'],Routes:['Name','District','Headquarters','Working days'],'MR types':['Name','Description']});
export const adminLabels:Record<string,string>={Dashboard:'Management overview',Team:'MR management',Customers:'Doctors & customers',Products:'Products & pricing',Samples:'Sample allotment',Expenses:'Expense approvals',Orders:'Order management',Settings:'Management settings'};
fields.Products=['Name','Pack','Species focus','MRP','PTR','PTS','GST %','Retail offer enabled','Retail offer rate','Sample cost',...([1,2,3].flatMap(i=>[`Scheme ${i} enabled`,`Scheme ${i} paid`,`Scheme ${i} free`])),'Visual aid URL'];
fields.Gifts=['Name','Unit cost','One per customer','Notes'];options['One per customer']=['Yes','No'];options['Retail offer enabled']=['No','Yes'];
for(const i of [1,2,3]){options[`Scheme ${i} enabled`]=['No','Yes'];numeric.push(`Scheme ${i} paid`,`Scheme ${i} free`)}numeric.push('Retail offer rate','Sample cost');
options.Action=['Check in','Check out'];
columns.Products=['Name','Pack','MRP','PTR','PTS','Retail offer rate','Scheme'];columns.Visits=['Customer','Date','Purpose','Status'];columns.Gifts=['Name','Unit cost','One per customer'];
singular.Gifts='gift material';descriptions.Gifts='Allot gifts, monitor costs and control repeat supply.';descriptions['Stock balance']='Stockist-wise product quantities and primary invoice values.';descriptions.WhatsApp='Visit thank-you messages and their delivery status.';
