import {audit} from '../../../lib/admin-audit';
import {admin,db,json,failure,sameOrigin,HttpError} from '../../../lib/server';
import {reportingData,makeReport,stateSQL} from '../../../lib/periods';
import {guard,indiaDay} from '../../../lib/operations';
import {digest} from '../../../lib/passwords';
import type {Member} from '../../../lib/permissions';
const valid=(m:unknown)=>typeof m==='string'&&/^20\d{2}-(0[1-9]|1[0-2])$/.test(m);
export async function GET(){try{await admin();return json({periods:(await db().prepare('SELECT * FROM period_locks ORDER BY month DESC').all()).results,events:(await db().prepare('SELECT * FROM period_events ORDER BY created DESC LIMIT 100').all()).results})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const a=await admin(),b=await req.json() as any;if(!valid(b.month))throw new HttpError(400,'Choose a month.');const now=new Date().toISOString();
 if(b.action==='reopen'){if(typeof b.reason!=='string'||b.reason.trim().length<5)throw new HttpError(400,'Record a reason for reopening.');if(await db().prepare('SELECT month FROM period_locks WHERE month>? AND closed=1').bind(b.month).first())throw new HttpError(409,'Reopen later closed months first to protect their opening stock.');await db().batch([audit(a,'Month reopened','Reporting period',b.month,{closed:true},{closed:false},b.reason),guard('version','EXISTS(SELECT 1 FROM period_locks WHERE month=? AND closed=1)',[b.month]),db().prepare('UPDATE period_locks SET closed=0,updated=?,admin_email=?,reason=? WHERE month=?').bind(now,a.email,b.reason,b.month),db().prepare('INSERT INTO period_events VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),b.month,'Reopened',a.email,b.reason,now)]);return json({ok:true})}
 if(!['review','close'].includes(b.action))throw new HttpError(400,'Choose Review, Close or Reopen.');if(b.month>=indiaDay().slice(0,7))throw new HttpError(400,'Only completed calendar months can be closed.');if(await db().prepare('SELECT month FROM period_locks WHERE month=? AND closed=1').bind(b.month).first())throw new HttpError(409,'This month is already closed.');
 const stamp=(await db().prepare(stateSQL).first<{stamp:string}>())!.stamp,data=await reportingData(),reps=(await db().prepare("SELECT * FROM members WHERE role='mr'").all<Member>()).results;
 const pendingOrders=data.invoices.filter(i=>i.kind==='secondary'&&i.status==='Placed'&&i.date.slice(0,7)<=b.month).length;
 const pendingEdits=(await db().prepare("SELECT COUNT(*) AS n FROM workflow_requests r JOIN invoices i ON i.id=r.record_id WHERE r.kind='order_edit' AND r.status='Pending' AND substr(i.date,1,7)<=?").bind(b.month).first<{n:number}>())!.n;
 const reports=reps.map(m=>({m,admin:makeReport(m,b.month,data,true),mr:makeReport(m,b.month,data,false)})),hash=await digest(stamp);
 if(b.action==='review'){if((await db().prepare(stateSQL).first<{stamp:string}>())!.stamp!==stamp)throw new HttpError(409,'Data changed while preparing this review. Retry.');return json({hash,pendingOrders,pendingEdits,month:b.month,summaries:reports.map(r=>r.admin.summary),note:'Resolve placed orders and pending order edits before closing. Closing archives the complete MR reports and locks sales, stock movements and targets.'})}
 if(b.hash!==hash)throw new HttpError(409,'Data changed since your review. Review the month again.');if(pendingOrders||pendingEdits)throw new HttpError(409,'Deliver or cancel placed orders and resolve pending edits before closing.');
 const closure=crypto.randomUUID(),statements=[guard('version',`(${stateSQL})=?`,[stamp]),guard('version',"NOT EXISTS(SELECT 1 FROM workflow_requests r JOIN invoices i ON i.id=r.record_id WHERE r.kind='order_edit' AND r.status='Pending' AND substr(i.date,1,7)<=?)",[b.month]),guard('version','NOT EXISTS(SELECT 1 FROM period_locks WHERE month=? AND closed=1)',[b.month])];
 for(const r of reports)statements.push(db().prepare('INSERT INTO period_reports(id,closure_id,month,mr_email,report,created) VALUES (?,?,?,?,?,?)').bind(closure+'|'+r.m.email,closure,b.month,r.m.email,JSON.stringify({admin:{...r.admin,closed:true,closedAt:now},mr:{...r.mr,closed:true,closedAt:now}}),now));
 statements.push(audit(a,'Month closed','Reporting period',b.month,{closed:false},{closed:true,closureId:closure},'Reviewed and approved'),db().prepare('INSERT INTO period_locks(month,closed,closure_id,updated,admin_email,reason) VALUES (?,1,?,?,?,?) ON CONFLICT(month) DO UPDATE SET closed=1,closure_id=excluded.closure_id,updated=excluded.updated,admin_email=excluded.admin_email,reason=excluded.reason').bind(b.month,closure,now,a.email,'Reviewed and approved'),db().prepare('INSERT INTO period_events VALUES (?,?,?,?,?,?)').bind(closure,b.month,'Closed',a.email,'Reviewed and approved',now));await db().batch(statements);return json({ok:true});
}catch(e){return failure(e)}}
