import {type ClientSession,type Db,type Document} from 'mongodb';
import {mongoClient,mongoDB} from './client';
import schema from './schema.json';
import {Parser,parse,mongoExpr,evaluate,split,fieldName,type Expr} from './expressions';
import {specialQuery} from './special';
export type Context={db:Db,session?:ClientSession};
export type Result={results:any[],meta:{changes:number},success:true};
export const result=(results:any[]=[],changes=0):Result=>({results,meta:{changes},success:true});
export function clean(d:any){if(!d)return d;const {_id,_json,...rest}=d;return rest;}
export function stored(d:any){const o={...d};delete o._json;const j:any={};for(const k of ['data','payload'])if(typeof o[k]==='string'){try{j[k]=JSON.parse(o[k])}catch{throw Error('Invalid JSON column '+k)}}o._json=j;return o;}
export function defaults(table:string){const cols=(schema as any)[table];if(!cols)throw Error('Unknown collection '+table);const out:any={};for(const c of cols){if(c.default!==null)out[c.name]=/^'.*'$/.test(c.default)?c.default.slice(1,-1).replaceAll("''","'"):Number(c.default);else if(!c.notnull)out[c.name]=null;}return out;}
export const options=(c:Context)=>c.session?{session:c.session}:{};
export async function rows(c:Context,table:string,filter:any={},sort:any={},limit?:number){const cursor=c.db.collection(table).find(filter,options(c)).sort(sort);if(limit)cursor.limit(limit);return cursor.toArray()}
export async function one(c:Context,table:string,filter:any={}){return c.db.collection(table).findOne(filter,options(c))}
export async function put(c:Context,table:string,d:any){return c.db.collection(table).insertOne(stored({...defaults(table),...d}),options(c))}
export async function replace(c:Context,table:string,d:any){return c.db.collection(table).replaceOne({_id:d._id},stored(d),options(c))}
function makeFilter(expr:string,args:any[]){return {$expr:mongoExpr(parse(expr,args))}}
export async function genericSelect(c:Context,q:string,args:any[]):Promise<Result>{
 const parts=split(q,' FROM ');if(parts.length!==2)throw Error('Unsupported SELECT '+q);const projection=parts[0].replace(/^SELECT /i,''),m=parts[1].match(/^(\w+)(?: WHERE (.*?))?(?: GROUP BY (.*?))?(?: ORDER BY (.*?))?(?: LIMIT (\d+))?$/i);if(!m)throw Error('Unsupported SELECT clause '+q);
 const [,table,where,group,order,limit]=m;if(!(schema as any)[table])throw Error('Unknown collection '+table);const pipeline:any[]=[];if(where)pipeline.push({$match:makeFilter(where,args)});else if(args.length)throw Error('Unused parameters '+q);
 const fields=split(projection),aggregate=!!group||fields.some(f=>/^(COUNT|SUM|MIN|MAX|COALESCE\(SUM)\(/i.test(f));
 if(aggregate){const groups=group?split(group):[],g:any={_id:groups.length?Object.fromEntries(groups.map(k=>[k,'$'+k])):null},p:any={_id:0};for(const f of fields){const a=f.match(/^(.*?)\s+AS\s+(\w+)$/i);const src=a?a[1]:f,name=a?a[2]:f;let z=src.match(/^(SUM|MIN|MAX|COUNT)\((.*?)\)$/i);if(src.match(/^COALESCE\(SUM\((\w+)\),0\)$/i))z=src.match(/^COALESCE\((SUM)\((\w+)\),0\)$/i);if(z){g[name]=z[1].toUpperCase()==='COUNT'?{$sum:1}:{['$'+z[1].toLowerCase()]:'$'+z[2]};p[name]=1}else if(groups.includes(src))p[name]='$_id.'+src;else throw Error('Unsupported aggregate '+f)}pipeline.push({$group:g},{$project:p});let found=await c.db.collection(table).aggregate(pipeline,options(c)).toArray();if(!found.length&&!group){const row:any={};for(const f of fields){const name=f.match(/ AS (\w+)$/i)?.[1]||f;row[name]=/COUNT|COALESCE/i.test(f)?0:null}found=[row]}return result(found);}
 if(order){const sort:any={},computed:any={};for(const [i,v]of split(order).entries()){const m=v.match(/^(.*?)(?: (ASC|DESC))?$/i)!;const e=parse(m[1]);if(e.kind==='field')sort[e.value==='rowid'?'_id':fieldName(e.value)]=m[2]?.toUpperCase()==='DESC'?-1:1;else{computed['__sort'+i]=mongoExpr(e);sort['__sort'+i]=m[2]?.toUpperCase()==='DESC'?-1:1}}if(Object.keys(computed).length)pipeline.push({$set:computed});pipeline.push({$sort:sort});if(Object.keys(computed).length)pipeline.push({$unset:Object.keys(computed)});}
 if(limit)pipeline.push({$limit:Number(limit)});
 if(projection==='*')pipeline.push({$unset:['_id','_json']});else{const p:any={_id:0};for(const f of fields){const a=f.match(/^(.*?)\s+AS\s+(\w+)$/i),src=a?a[1]:f,name=a?a[2]:f;if(/^\w+$/.test(src))p[name]='$'+src;else p[name]=mongoExpr(parse(src));}pipeline.push({$project:p})}
 return result(await c.db.collection(table).aggregate(pipeline,options(c)).toArray());
}
async function genericWrite(c:Context,q:string,args:any[]):Promise<Result>{
 const returning=q.match(/ RETURNING (\w+)$/i)?.[1];if(returning)q=q.replace(/ RETURNING \w+$/i,'');
 if(q.startsWith('INSERT INTO ')){const m=q.match(/^INSERT INTO (\w+)\s*(?:\((.*?)\))? VALUES \((.*?)\)(?: ON CONFLICT\((\w+)\) DO UPDATE SET (.*))?$/i);if(!m)throw Error('Unsupported INSERT '+q);const [,table,columns,values,key,updates]=m,cols=columns?split(columns):(schema as any)[table].map((x:any)=>x.name),p=new Parser(values,args),incoming:any={};for(let i=0;i<cols.length;i++){incoming[cols[i]]=evaluate(p.expr(),{});if(i<cols.length-1)p.expect(',')}if(p.p!==args.length||p.i!==p.t.length)throw Error('INSERT parameter mismatch');let doc=key?await one(c,table,{[key]:incoming[key]}):null;if(doc){const original={...doc,excluded:incoming};for(const x of split(updates)){const pair=split(x,'=');doc[pair[0]]=evaluate(parse(pair.slice(1).join('=')),original)}await replace(c,table,doc);}else{doc={...defaults(table),...incoming};await put(c,table,doc)}return result(returning?[{[returning]:doc![returning]}]:[],1);}
 const m=q.match(/^(UPDATE (\w+) SET (.*?)|DELETE FROM (\w+)) WHERE (.*)$/i);if(!m)throw Error('Unsupported mutation '+q);const table=m[2]||m[4];let used=0;const updates:any[]=[];if(m[2])for(const x of split(m[3])){const pair=split(x,'='),p=new Parser(pair.slice(1).join('='),args.slice(used)),expr=p.expr();if(p.i!==p.t.length)throw Error('Unsupported update');used+=p.p;updates.push([pair[0].trim(),expr]);}const filter=makeFilter(m[5],args.slice(used)),docs=await rows(c,table,filter);const found=[];for(const d of docs){if(m[2]){const next={...d};for(const [k,e] of updates)next[k]=evaluate(e,d);await replace(c,table,next)}else await c.db.collection(table).deleteOne({_id:d._id},options(c));if(returning)found.push({[returning]:d[returning]})}return result(found,docs.length);
}
export async function execute(c:Context,q:string,args:any[]=[]):Promise<Result>{const special=await specialQuery(c,q,args);if(special)return special;return q.startsWith('SELECT ')?genericSelect(c,q,args):genericWrite(c,q,args);}
// Serialize business writes across Node processes. The shared revision document
// prevents snapshot write-skew (e.g. a period closing alongside a stock posting).
export async function transaction<T>(work:(c:Context)=>Promise<T>){const client=await mongoClient(),db=await mongoDB(),session=client.startSession();try{return await session.withTransaction(async()=>{const lock=await db.collection('_control').updateOne({_id:'ledger' as any},{$inc:{revision:1}},{session});if(lock.matchedCount!==1)throw Error('Run db:setup before starting the application');return work({db,session})},{readConcern:{level:'snapshot'},writeConcern:{w:'majority'},readPreference:'primary'});}catch(e:any){if(e.code===11000)throw Error('UNIQUE constraint: duplicate entry');throw e}finally{await session.endSession()}}
export class Statement{constructor(public query:string,public args:any[]=[]){this.query=query.trim().replace(/\s+/g,' ')}bind(...args:any[]){return new Statement(this.query,args)}async result(){return this.query.startsWith('SELECT ')?execute({db:await mongoDB()},this.query,this.args):transaction(c=>execute(c,this.query,this.args))}async first<T=Record<string,any>>(){return (await this.result()).results[0] as T||null}async all<T=Record<string,any>>(){const r=await this.result();return {...r,results:r.results as T[]}}async run(){return this.result()}}
export const mongoDatabase={prepare:(q:string)=>new Statement(q),batch:(statements:Statement[])=>transaction(async c=>{const out:Result[]=[];for(const s of statements)out.push(await execute(c,s.query,s.args));return out})};
