/* Restricted legacy query expressions compiled to native MongoDB filters.
 * This is not a general SQL endpoint. Query text is application-owned only.
 * Unsupported syntax fails closed; bound values are never parsed as code.
 */
export type Expr={kind:string,value?:any,args?:Expr[]};
export const lit=(value:any):Expr=>({kind:'literal',value});
export function tokens(source:string){const out:string[]=[];let i=0;while(i<source.length){if(/\s/.test(source[i])){i++;continue}const m=source.slice(i).match(/^(?:'(?:''|[^'])*'|>=|<=|<>|!=|\|\||[A-Za-z_][\w.]*|\d+(?:\.\d+)?|[?(),=<>+*/-])/);if(!m)throw Error('Unsupported query token: '+source.slice(i,40));out.push(m[0]);i+=m[0].length;}return out;}
export class Parser{
 t:string[];i=0;p=0;constructor(source:string,public values:any[]=[]){this.t=tokens(source)}
 peek(){return this.t[this.i]?.toUpperCase()} take(){return this.t[this.i++]}
 expect(s:string){if(this.peek()!==s)throw Error('Expected '+s+', got '+this.peek());this.i++}
 expr(min=0):Expr{let a:Expr;const t=this.take();if(t===undefined)throw Error('Missing expression');if(t==='?'){if(this.p>=this.values.length)throw Error('Missing parameter');a=lit(this.values[this.p++])}else if(t.startsWith("'"))a=lit(t.slice(1,-1).replaceAll("''","'"));else if(/^\d/.test(t))a=lit(Number(t));else if(t==='('){a=this.expr();this.expect(')')}else if(['NOT','-','+'].includes(t.toUpperCase()))a={kind:t.toUpperCase()==='NOT'?'not':t==='-'?'neg':'pos',args:[this.expr(6)]};else if(t.toUpperCase()==='NULL')a=lit(null);else if(this.peek()==='('){this.take();const args:Expr[]=[];if(this.peek()!==')')do{args.push(this.expr());if(this.peek()!==',')break;this.take()}while(true);this.expect(')');a={kind:t.toLowerCase(),args};}else a={kind:'field',value:t};
 const precedence:any={OR:1,AND:2,'=':3,'<>':3,'!=':3,'>':3,'<':3,'>=':3,'<=':3,IS:3,IN:3,LIKE:3,'||':4,'+':4,'-':4,'*':5,'/':5};while(this.peek()&&precedence[this.peek()!]>=min){const op=this.take().toUpperCase();if(op==='IS'){let not=false;if(this.peek()==='NOT'){this.take();not=true}this.expect('NULL');a={kind:not?'notnull':'isnull',args:[a]};continue}if(op==='IN'){this.expect('(');const arr=[a];do{arr.push(this.expr());if(this.peek()!==',')break;this.take()}while(true);this.expect(')');a={kind:'in',args:arr};continue}a={kind:op.toLowerCase(),args:[a,this.expr(precedence[op]+1)]}}return a;}
}
export function parse(s:string,values:any[]=[]){const p=new Parser(s,values),e=p.expr();if(p.i!==p.t.length)throw Error('Unsupported expression: '+s);return e;}
export function pathOf(v:string){if(!v.startsWith('$.'))throw Error('Unsupported JSON path');const s=v.slice(2);return s.startsWith('"')?JSON.parse(s):s;}
export function fieldName(s:string){return s.split('.').at(-1)!;}
const literal=(x:any)=>({$literal:x});
export function mongoExpr(e:Expr):any{const a=e.args||[],m=a.map(mongoExpr);switch(e.kind){case 'literal':return literal(e.value);case 'field':return '$'+(e.value==='rowid'?'_id':fieldName(e.value));case 'json_extract':{if(a[0].kind!=='field'||a[1].kind!=='literal')throw Error('Unsupported JSON expression');return '$_json.'+fieldName(a[0].value)+'.'+pathOf(a[1].value)}case 'coalesce':return {$ifNull:m};case 'lower':return {$toLower:m[0]};case 'trim':return {$trim:{input:{$ifNull:[m[0],'']}}};case 'substr':return {$substrCP:[{$ifNull:[m[0],'']},{$subtract:[m[1],1]},m[2]]};case 'not':return {$not:[m[0]]};case 'neg':return {$multiply:[-1,m[0]]};case 'pos':return m[0];case 'isnull':return {$eq:[{$ifNull:[m[0],null]},null]};case 'notnull':return {$ne:[{$ifNull:[m[0],null]},null]};case 'like':{if(a[1].kind!=='literal'||typeof a[1].value!=='string')throw Error('LIKE requires a bound pattern');const pattern='^'+a[1].value.split('').map((c:string)=>c==='%'?'.*':c==='_'?'.':c.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('')+'$';return {$regexMatch:{input:{$ifNull:[m[0],'']},regex:pattern,options:'i'}}}case 'in':return {$in:[m[0],m.slice(1)]};}
 const op:any={'=':'$eq','<>':'$ne','!=':'$ne','>':'$gt','<':'$lt','>=':'$gte','<=':'$lte',and:'$and',or:'$or','+':'$add','-':'$subtract','*':'$multiply','/':'$divide','||':'$concat'};if(op[e.kind]){const v={[op[e.kind]]:m};if(['=','<>','!=','>','<','>=','<='].includes(e.kind))return {$and:[{$ne:[{$ifNull:[m[0],null]},null]},{$ne:[{$ifNull:[m[1],null]},null]},v]};return v}throw Error('Unsupported expression '+e.kind);}
export function evaluate(e:Expr,row:any):any{const a=e.args||[],v=a.map(x=>evaluate(x,row));switch(e.kind){case 'literal':return e.value;case 'field':return e.value.startsWith('excluded.')?row.excluded?.[fieldName(e.value)]:row[fieldName(e.value)];case 'json_extract':{const o=typeof v[0]==='string'?JSON.parse(v[0]):v[0];return o?.[pathOf(v[1])]??null}case 'json_set':{const o=JSON.parse(v[0]);for(let i=1;i<v.length;i+=2)o[pathOf(v[i])]=v[i+1];return JSON.stringify(o)}case 'coalesce':return v.find(x=>x!=null)??null;case '+':return v[0]+v[1];case '-':return v[0]-v[1];case '*':return v[0]*v[1];case '/':return v[0]/v[1];case 'neg':return -v[0];case 'pos':return v[0];case 'lower':return String(v[0]).toLowerCase();case 'trim':return String(v[0]).trim();default:throw Error('Unsupported update expression '+e.kind)}}
// Split only outside quoted strings and parentheses.
export function split(s:string,sep=','){const out:string[]=[];let quote=false,depth=0,start=0;for(let i=0;i<s.length;i++){if(s[i]==="'"){if(quote&&s[i+1]==="'"){i++;continue}quote=!quote}if(quote)continue;if(s[i]==='(')depth++;if(s[i]===')')depth--;if(depth===0&&s.slice(i,i+sep.length).toUpperCase()===sep.toUpperCase()){out.push(s.slice(start,i).trim());start=i+sep.length;i+=sep.length-1}}out.push(s.slice(start).trim());return out;}
