import {type Context,result,rows,one,put,replace,clean,options,execute,genericSelect} from './database';
const exists=async(c:Context,t:string,f:any)=>!!await one(c,t,f);
const byOwner=(email:string,user:string)=>({$or:[{assigned_to:email},{assigned_to:'',owner:user}]});
const data=(r:any)=>r?JSON.parse(r.data):{};
const sum=async(c:Context,t:string,f:any,field='quantity')=>(await rows(c,t,f)).reduce((n,r)=>n+(Number(r[field])||0),0);
async function lastAttendance(c:Context,date:string,email:string,user:string){return (await rows(c,'records',{kind:'Attendance','_json.data.Date':date,...byOwner(email,user)},{created:-1,_id:-1},1))[0]}
async function pendingEdits(c:Context,month:string){const requests=await rows(c,'workflow_requests',{kind:'order_edit',status:'Pending'});let n=0;for(const r of requests){const i=await one(c,'invoices',{id:r.record_id});if(i&&i.date.slice(0,7)<=month)n++}return n;}
async function stockRows(c:Context,withDate:boolean){const list=await rows(c,'stock_balances');const out=[];for(const b of list){const f={stockist_id:b.stockist_id,product_id:b.product_id};out.push({...clean(b),reserved:await sum(c,'stock_reservations',f),...(withDate?{last_movement:(await rows(c,'stock_movements',f,{created:-1},1))[0]?.created??null}:{})})}return out;}
async function stamp(c:Context){const columns:any={invoices:['id','revision','status','accepted'],records:['id','data','assigned_to'],benefit_movements:['id','quantity','cost'],commitments:['id','fulfilled'],stock_movements:['id','quantity'],members:['email','target','route_ids','stockist_ids']};const out=[];for(const [table,fields]of Object.entries(columns) as [string,string[]][]){out.push((await rows(c,table,{}, {[fields[0]]:1})).map(r=>fields.map(f=>r[f]??null)))}return JSON.stringify(out)}
async function condition(c:Context,s:string,a:any[]):Promise<boolean>{
 if(s.startsWith('(SELECT json_array('))return await stamp(c)===a[0];
 if(s.startsWith('COALESCE((SELECT quantity FROM stock_balances'))return ((await one(c,'stock_balances',{stockist_id:a[0],product_id:a[1]}))?.quantity||0)>=await sum(c,'stock_reservations',{stockist_id:a[2],product_id:a[3]});
 if(s.startsWith('NOT EXISTS(SELECT 1 FROM benefit_balances b JOIN')){const m=await one(c,'benefit_movements',{id:a[0]});if(!m)return true;const b=await one(c,'benefit_balances',{id:`${m.kind}|${m.mr_email}|${m.item_id}`});return !b||b.quantity>=0&&b.value>=0;}
 if(s.startsWith('NOT(COALESCE(')){const r=await one(c,'records',{id:a[0]});return !(String(data(r)['One per customer']??'Yes')==='Yes'&&await exists(c,'benefit_movements',{kind:'gift',movement:'issue',item_id:a[1],customer_id:a[2]}));}
 if(s.startsWith('COALESCE((SELECT fulfilled')){const r=await one(c,'commitments',{id:a[0]});return !!r&&r.fulfilled>=0&&r.fulfilled<=r.quantity;}
 if(s.startsWith('COALESCE((SELECT json_extract'))return data(await lastAttendance(c,a[2],a[0],a[1])).Action==='Check in';
 if(s.startsWith('NOT EXISTS(SELECT 1 FROM workflow_requests r JOIN'))return await pendingEdits(c,a[0])===0;
 const e=s.match(/^(NOT )?EXISTS\((SELECT .*?)\)$/);if(e){const n=(await execute(c,e[2],a)).results.length>0;return e[1]?!n:n}throw Error('Unsupported ledger condition: '+s);
}
async function insertRecordWhen(c:Context,q:string,a:any[]){const update=q.startsWith('UPDATE'),r:any=update?await one(c,'records',{id:a[2]}):{id:a[0],owner:a[1],kind:a[2],data:a[3],created:a[4],assigned_to:a[5]};if(!r)return result();const next=update?{...r,data:a[0],assigned_to:a[1]}:r,offset=update?3:6,[date,email,user]=a.slice(offset),d=data(next);const month=q.match(/month>='([0-9-]+)'/)?.[1];if(!month)throw Error('Missing attendance period');if(await exists(c,'period_locks',{closed:1,month:{$gte:month}}))return result();const checked=data(await lastAttendance(c,date,email,user)).Action==='Check in';const required=d.Action==='Check out'||next.kind==='Visits';if(checked!==required)return result();
 if(next.kind==='Attendance'){if(await exists(c,'records',{kind:'Attendance','_json.data.Date':date,'_json.data.Action':d.Action,...byOwner(email,user)}))return result();if(d.Action==='Check out'&&await exists(c,'records',{kind:'Visits','_json.data.Date':date,'_json.data.Status':{$ne:'Closed'},...byOwner(email,user)}))return result();}
 if(update)await replace(c,'records',next);else await put(c,'records',next);return result([{id:next.id}],1);
}
export async function specialQuery(c:Context,q:string,a:any[]){
 if(q.startsWith('SELECT json_array('))return result([{stamp:await stamp(c)}]);
 if(q.startsWith('INSERT OR REPLACE INTO ledger_guards')){const match=q.match(/^INSERT OR REPLACE INTO ledger_guards\(id,(\w+)\) VALUES \('transaction',CASE WHEN \((.*)\) THEN 1 ELSE 0 END\)$/);if(!match)throw Error('Invalid ledger guard');const messages:any={stock:'INSUFFICIENT_STOCK',benefit:'INSUFFICIENT_ALLOTMENT',gift:'GIFT_ALREADY_SUPPLIED',commitment:'COMMITMENT_EXCEEDED',attendance:'ATTENDANCE_REQUIRED',period:'PERIOD_CLOSED',version:'STALE_REVIEW'};if(!await condition(c,match[2],a))throw Error(messages[match[1]]||'Invalid guard');return result([],1);}
 if(q.startsWith('SELECT m.*, c.username FROM sessions')){const s=await one(c,'sessions',{token_hash:a[0],expires:{$gt:a[1]}});if(!s)return result();const m=await one(c,'members',{email:s.email}),cred=await one(c,'credentials',{email:s.email});return result(m&&cred?[{...clean(m),username:cred.username}]:[]);}
 if(q.startsWith('SELECT c.email,c.password_hash,m.status,m.role')){const cred=await one(c,'credentials',{username:a[0]});const m=cred?await one(c,'members',{email:cred.email}):null;return result(m?[{email:cred!.email,password_hash:cred!.password_hash,status:m.status,role:m.role}]:[]);}
 if(q.startsWith('SELECT m.*, c.username FROM members')){const out=[];for(const m of await rows(c,'members',{}, {role:1,name:1}))out.push({...clean(m),username:(await one(c,'credentials',{email:m.email}))?.username??null});return result(out);}
 if(q.startsWith('INSERT INTO login_limits ')){const old=await one(c,'login_limits',{key:a[0]});const expired=!old||old.expires<=a[2],d={...old,key:a[0],attempts:expired?1:old.attempts+1,expires:expired?a[1]:old.expires};if(old)await replace(c,'login_limits',d);else await put(c,'login_limits',d);return result([{attempts:d.attempts}],1);}
 if(q.startsWith('INSERT INTO sessions ')&&q.includes(' SELECT ')){const cred=await one(c,'credentials',{email:a[2],password_hash:a[3]});if(!cred)throw Error('STALE_REVIEW');await put(c,'sessions',{token_hash:a[0],email:cred.email,expires:a[1]});return result([],1);}
 if(q.startsWith('SELECT b.*,COALESCE('))return result(await stockRows(c,q.includes('last_movement')));
 if(q.startsWith('SELECT r.mr_email,r.report FROM period_reports')){const out=[];for(const r of await rows(c,'period_reports',{month:a[0]}))if(await exists(c,'period_locks',{closure_id:r.closure_id,closed:1}))out.push({mr_email:r.mr_email,report:r.report});return result(out);}
 if(q.startsWith('SELECT COUNT(*) AS n FROM workflow_requests r JOIN'))return result([{n:await pendingEdits(c,a[0])}]);
 if(q.startsWith('SELECT c.*,i.number AS order_number')){const out=[];for(const p of await rows(c,'commitments',{mr_email:a[0],customer_id:a[1]},{created:-1})){const i=await one(c,'invoices',{id:p.invoice_id,status:{$ne:'Cancelled'}});if(i)out.push({...clean(p),order_number:i.number})}return result(out);}
 if(q.startsWith('SELECT * FROM mr_drafts WHERE mr_email=? AND status=')&&q.includes('NOT EXISTS')){const out=[];for(const d of await rows(c,'mr_drafts',{mr_email:a[0],status:'Active'},{updated:-1})){if(d.kind==='order'&&await exists(c,'invoices',{id:d.id}))continue;if(d.kind==='visit'&&await exists(c,'records',{id:d.id}))continue;if(d.kind==='visit_close'&&await exists(c,'records',{id:JSON.parse(d.payload).visitId,'_json.data.Status':'Closed'}))continue;out.push(clean(d))}return result(out);}
 if(q.startsWith('SELECT json_extract(c.data')){const v=await one(c,'records',{id:a[0]}),customer=v?await one(c,'records',{id:data(v)['Customer ID']}):null;return result(customer?[{mobile:data(customer)['Mobile 1']??null,phone:data(customer).Phone??null}]:[]);}
 if(q.startsWith('SELECT id FROM stock_movements')&&q.includes(' UNION ')){for(const [table,f]of [['stock_movements',{$or:[{stockist_id:a[0]},{product_id:a[1]}]}],['benefit_movements',{$or:[{item_id:a[2]},{customer_id:a[3]}]}],['invoices',{customer_id:a[4]}]] as [string,any][]){const d=await one(c,table,f);if(d)return result([{id:d.id}])}return result();}
 if(q.startsWith('INSERT INTO benefit_balances')&&q.includes(' SELECT ')){const m=await one(c,'benefit_movements',{id:a[0]});if(!m)return result();const id=`${m.kind}|${m.mr_email}|${m.item_id}`,b=await one(c,'benefit_balances',{id}),next={...b,id,kind:m.kind,mr_email:m.mr_email,item_id:m.item_id,quantity:(b?.quantity||0)+m.quantity,value:(b?.value||0)+m.cost};if(b)await replace(c,'benefit_balances',next);else await put(c,'benefit_balances',next);return result([],1);}
 if(q.startsWith('INSERT INTO records')&&q.includes("SELECT 'benefit:'")){const m=await one(c,'benefit_movements',{id:a[0]});if(!m)return result();const mr=await one(c,'members',{email:m.mr_email}),p=await one(c,'records',{id:m.item_id}),customer=await one(c,'records',{id:m.customer_id});await put(c,'records',{id:'benefit:'+m.id,owner:mr?.user_id||'',kind:'Samples',data:JSON.stringify({Date:new Date(Date.parse(m.created)+19800000).toISOString().slice(0,10),Product:data(p).Name??null,Customer:data(customer).Name||'',Movement:m.movement==='allocate'?'Issued to rep':m.movement==='return'?'Returned':'Given to customer',Quantity:String(Math.abs(m.quantity)),'Unit cost':String(Math.abs(m.cost)/Math.abs(m.quantity)/100),Representative:mr?.name??null,'Ledger ID':m.id}),created:m.created,assigned_to:m.mr_email});return result([],1);}
 if(q.startsWith('INSERT INTO benefit_movements')&&q.includes('-COALESCE')){const b=await one(c,'benefit_balances',{id:a[9],quantity:{$gte:a[10]}}),keys=['id','kind','movement','mr_email','item_id','customer_id','visit_id','quantity'];const d:any=Object.fromEntries(keys.map((k,i)=>[k,a[i]]));d.cost=b?-Math.round(b.value*a[8]/b.quantity):0;d.gps=a[11];d.created=a[12];await put(c,'benefit_movements',d);return result([],1);}
 if((q.startsWith('INSERT INTO records')||q.startsWith('UPDATE records'))&&q.includes('attendanceActionSQL'))throw Error('Unexpanded attendance query');
 if((q.startsWith('INSERT INTO records')||q.startsWith('UPDATE records'))&&q.includes("COALESCE((SELECT json_extract(data,'$.Action')"))return insertRecordWhen(c,q,a);
 // Historical sample records can only be removed by Admin; new ledger writes use benefits.
 if(q.startsWith('DELETE FROM records WHERE id = ? AND (SELECT COALESCE(SUM(CASE')){const [id,email,product,exclude,month]=a;if(await exists(c,'period_locks',{closed:1,month:{$gte:month}}))return result();let balance=0;for(const r of await rows(c,'records',{kind:'Samples',assigned_to:email,'_json.data.Product':product,id:{$ne:exclude}})){const d=data(r);balance+=(d.Movement==='Issued to rep'?1:-1)*Number(d.Quantity||0)}if(balance<0)return result();const r=await c.db.collection('records').deleteOne({id},options(c));return result(r.deletedCount?[{id}]:[],r.deletedCount);}
 return null;
}
