import {z} from 'zod';
import {member,db,json,failure,sameOrigin,HttpError,notification} from '../../../lib/server';
import {record,guard,indiaDay,benefitPosting} from '../../../lib/operations';
import {periodGuard} from '../../../lib/periods';
import {OWNER_EMAIL} from '../../../lib/permissions';
import {audit} from '../../../lib/admin-audit';
export async function GET(){try{const m=await member();const list=(await db().prepare("SELECT * FROM workflow_requests WHERE kind='benefit_request' ORDER BY created DESC").all<any>()).results.filter(r=>m.role==='admin'||r.mr_email===m.email).map(r=>({...r,body:JSON.parse(r.body)}));return json({requests:list})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const m=await member(),raw=await req.json() as any;if(raw.action==='request'){if(m.role!=='mr')throw new HttpError(403,'MR accounts submit requests.');const b=z.object({id:z.string().uuid(),kind:z.enum(['sample','gift']),itemId:z.string().min(1),qty:z.number().int().min(1).max(100000),purpose:z.string().trim().min(3).max(2000)}).parse(raw);const item=await record(b.itemId,b.kind==='sample'?'Products':'Gifts');const old=await db().prepare('SELECT * FROM workflow_requests WHERE id=?').bind(b.id).first<any>();if(old){if(old.mr_email!==m.email||old.kind!=='benefit_request')throw new HttpError(403,'Request ID unavailable.');return json({ok:true});}const body={...b,itemName:item.details.Name};await db().batch([db().prepare("INSERT INTO workflow_requests(id,kind,mr_email,record_id,body,status,created) VALUES (?,'benefit_request',?,?,?,'Pending',?)").bind(b.id,m.email,b.itemId,JSON.stringify(body),new Date().toISOString()),notification(OWNER_EMAIL,`${b.kind==='sample'?'Sample':'Gift'} allotment requested`,`${m.name} · ${item.details.Name} · ${b.qty} units`,b.kind==='sample'?'Samples':'Gifts',b.id)]);return json({ok:true});}
 if(m.role!=='admin')throw new HttpError(403,'Only Admin can review requests.');const b=z.object({id:z.string().uuid(),action:z.enum(['allot','reject']),reason:z.string().trim().min(3).max(1000),qty:z.number().int().min(1).max(100000).optional(),unitCost:z.number().min(0).max(10000000).optional()}).parse(raw);const r=await db().prepare("SELECT * FROM workflow_requests WHERE id=? AND kind='benefit_request' AND status='Pending'").bind(b.id).first<any>();if(!r)throw new HttpError(409,'This request has already been reviewed.');const body=JSON.parse(r.body),now=new Date().toISOString(),statements=[guard('version',"EXISTS(SELECT 1 FROM workflow_requests WHERE id=? AND status='Pending')",[r.id])];
 if(b.action==='allot'){if(b.qty===undefined||b.unitCost===undefined)throw new HttpError(400,'Enter allotment quantity and cost.');if(!await db().prepare("SELECT email FROM members WHERE email=? AND role='mr' AND status='active'").bind(r.mr_email).first())throw new HttpError(400,'MR account must be active.');await record(body.itemId,body.kind==='sample'?'Products':'Gifts');const movementId='request:'+r.id;statements.push(periodGuard(indiaDay()),db().prepare("INSERT INTO benefit_movements(id,kind,movement,mr_email,item_id,quantity,cost,created) VALUES (?,?,'allocate',?,?,?,?,?)").bind(movementId,body.kind,r.mr_email,body.itemId,b.qty,Math.round(b.qty*b.unitCost*100),now),...benefitPosting(movementId,body.kind));}
 const status=b.action==='allot'?'Allotted':'Rejected',updated={...body,...(b.action==='allot'?{allottedQty:b.qty,unitCost:b.unitCost}: {})};statements.push(db().prepare('UPDATE workflow_requests SET status=?,reviewed=?,reason=?,body=? WHERE id=?').bind(status,now,b.reason,JSON.stringify(updated),r.id),audit(m,`Allotment request ${status.toLowerCase()}`,'Benefits',r.id,body,updated,b.reason),notification(r.mr_email,`${body.kind==='sample'?'Sample':'Gift'} request ${status.toLowerCase()}`,`${body.itemName} · ${b.reason}`,body.kind==='sample'?'Samples':'Gifts',r.id));await db().batch(statements);return json({ok:true});
 }catch(e){if(e instanceof z.ZodError)return failure(new HttpError(400,'Check quantity, purpose and review details.'));return failure(e)}}
